### ISSUE TITLE
unittests 报错 No module named 'tests.op_test'

### ISSUE THREAD

**Issue by PeiyuLau** [PaddlePaddle/PaddleCustomDevice#1030]
执行命令：
cd PaddleCustomDevice/backends/mlu
bash tools/compile.sh
cd build && ctest -R test_arg_max_op_mlu -V

报错：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/135964669/669aecc0-61d4-4386-9f83-01866cbe409d)

请问怎么解决？

**Comment by qili93** [comment]
您能贴一下完整输出吗？比如下面的截图里面会有PYTHONPATH的输出

<img width="981" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/16605440/89cb9a7a-c314-43d6-8b91-e967af014966">



这里PYTHONPATH里面包含的 /work/PaddleCustomDevice/backends/npu/../../python/tests 这个路径下是会包含单测依赖的op_test.py文件

<img width="612" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/16605440/2455de7c-a47e-49d0-97b7-9c048ea4c897">

**Comment by PeiyuLau** [comment]
已解决，感谢。
