### ISSUE TITLE
华为910A 编译报错：include "unsupported/Eigen/CXX11/Tensor

### ISSUE THREAD

**Issue by Jakin-huang** [PaddlePaddle/PaddleCustomDevice#1177]
/opt/py39/lib/python3.9/site-packages/paddle/include/paddle/phi/kernels/funcs/eigen/extensions.h:23:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "unsupported/Eigen/CXX11/Tensor"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/paddle-custom-npu.dir/build.make:257: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/argsort_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/argsort_kernel.cc.o] Error 1
CMakeFiles/paddle-custom-npu.dir/build.make:453: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/contiguous_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/contiguous_kernel.cc.o] Error 1
CMakeFiles/paddle-custom-npu.dir/build.make:439: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/concat_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/concat_kernel.cc.o] Error 1
CMakeFiles/paddle-custom-npu.dir/build.make:173: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/add_n_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/add_n_kernel.cc.o] Error 1
CMakeFiles/paddle-custom-npu.dir/build.make:411: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/coalesce_tensor_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/coalesce_tensor_kernel.cc.o] Error 1
CMakeFiles/Makefile2:159: recipe for target 'CMakeFiles/paddle-custom-npu.dir/all' failed
make[1]: *** [CMakeFiles/paddle-custom-npu.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
+ make_error=2
+ '[' 2 '!=' 0 ']'
+ echo 'Make Error Found !!!'
Make Error Found !!!
+ exit 7

**Comment by Jakin-huang** [comment]
当配置了Eigen后报错如下：

/opt/py39/lib/python3.9/site-packages/paddle/include/paddle/phi/kernels/funcs/eigen/extensions.h:378:49: error: ‘expm1’ is not a template function
 HOSTDEVICE inline float16 expm1(const float16& a) {
                                                 ^
/opt/py39/lib/python3.9/site-packages/paddle/include/paddle/phi/kernels/funcs/eigen/extensions.h:378:49: error: ‘expm1’ is not a template function
 HOSTDEVICE inline float16 expm1(const float16& a) {

CMakeFiles/paddle-custom-npu.dir/build.make:285: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/batch_norm_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/batch_norm_kernel.cc.o] Error 1
CMakeFiles/paddle-custom-npu.dir/build.make:117: recipe for target 'CMakeFiles/paddle-custom-npu.dir/kernels/activation_kernel.cc.o' failed
make[2]: *** [CMakeFiles/paddle-custom-npu.dir/kernels/activation_kernel.cc.o] Error 1
CMakeFiles/Makefile2:159: recipe for target 'CMakeFiles/paddle-custom-npu.dir/all' failed
make[1]: *** [CMakeFiles/paddle-custom-npu.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
+ make_error=2
+ '[' 2 '!=' 0 ']'
+ echo 'Make Error Found !!!'
Make Error Found !!!
+ exit 7

**Comment by YanhuiDua** [comment]
你好，这个问题我们正在修复中，修复后在这里给出修复PR哈～

**Comment by parap1uie-s** [comment]
Same issue

**Comment by YanhuiDua** [comment]
你好，Paddle侧修复PR在这里，https://github.com/PaddlePaddle/Paddle/pull/63757，先安装下昨天产出的daily build的paddlepaddle-cpu whl包，再重新编译下PaddleCustomDevice

**Comment by parap1uie-s** [comment]
> 你好，Paddle侧修复PR在这里，[https://github.com/PaddlePaddle/Paddle/pull/63757，先安装下昨天产出的daily](https://github.com/PaddlePaddle/Paddle/pull/63757%EF%BC%8C%E5%85%88%E5%AE%89%E8%A3%85%E4%B8%8B%E6%98%A8%E5%A4%A9%E4%BA%A7%E5%87%BA%E7%9A%84daily) build的paddlepaddle-cpu whl包，再重新编译下PaddleCustomDevice

明天https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html下的whl会更新吗？

**Comment by YanhuiDua** [comment]
会的 这个是daily build的whl包

**Comment by Jakin-huang** [comment]
截止到2024/4/25 09:31 从https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl下载的还是无法解决。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/17819399/6b842dcd-0242-4a7e-ba94-a0c42d754a39)
如果不是这个链接下载，麻烦提供下：，https://github.com/PaddlePaddle/Paddle/pull/63757%EF%BC%8C%E5%85%88%E5%AE%89%E8%A3%85%E4%B8%8B%E6%98%A8%E5%A4%A9%E4%BA%A7%E5%87%BA%E7%9A%84daily build的paddlepaddle-cpu whl包具体地址，实在没看明白或者如何操作

**Comment by YanhuiDua** [comment]
我看下

**Comment by YanhuiDua** [comment]
这个是修复的PR:https://github.com/PaddlePaddle/Paddle/pull/63839；刚刚合入的。这个地址的whl包明天才会更新，https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl，可以源码编译下Paddle

**Comment by parap1uie-s** [comment]
> 这个是修复的PR:[https://github.com/PaddlePaddle/Paddle/pull/63839；刚刚合入的。这个地址的whl包明天才会更新，https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl，可以源码编译下Paddle](https://github.com/PaddlePaddle/Paddle/pull/63839%EF%BC%9B%E5%88%9A%E5%88%9A%E5%90%88%E5%85%A5%E7%9A%84%E3%80%82%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E7%9A%84whl%E5%8C%85%E6%98%8E%E5%A4%A9%E6%89%8D%E4%BC%9A%E6%9B%B4%E6%96%B0%EF%BC%8Chttps://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E4%B8%8BPaddle)

4月26日，编译仍然报错

**Comment by YanhuiDua** [comment]
> > 这个是修复的PR:[https://github.com/PaddlePaddle/Paddle/pull/63839；刚刚合入的。这个地址的whl包明天才会更新，https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl，可以源码编译下Paddle](https://github.com/PaddlePaddle/Paddle/pull/63839%EF%BC%9B%E5%88%9A%E5%88%9A%E5%90%88%E5%85%A5%E7%9A%84%E3%80%82%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E7%9A%84whl%E5%8C%85%E6%98%8E%E5%A4%A9%E6%89%8D%E4%BC%9A%E6%9B%B4%E6%96%B0%EF%BC%8Chttps://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E4%B8%8BPaddle)
> 
> 4月26日，编译仍然报错

官网的aarch64的whl包没有更新，我这里编译一个给你吧，确认下是需要py39+aarch64的吗？

**Comment by parap1uie-s** [comment]
> > > 这个是修复的PR:[https://github.com/PaddlePaddle/Paddle/pull/63839；刚刚合入的。这个地址的whl包明天才会更新，https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl，可以源码编译下Paddle](https://github.com/PaddlePaddle/Paddle/pull/63839%EF%BC%9B%E5%88%9A%E5%88%9A%E5%90%88%E5%85%A5%E7%9A%84%E3%80%82%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E7%9A%84whl%E5%8C%85%E6%98%8E%E5%A4%A9%E6%89%8D%E4%BC%9A%E6%9B%B4%E6%96%B0%EF%BC%8Chttps://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp39-cp39-linux_aarch64.whl%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E4%B8%8BPaddle)
> > 
> > 
> > 4月26日，编译仍然报错
> 
> 官网的aarch64的whl包没有更新，我这里编译一个给你吧，确认下是需要py39+aarch64的吗？

不紧急，等官网更新吧

**Comment by YanhuiDua** [comment]
Hi，这是develop的paddle-py38-aarch64的whl包，可以试下：https://ecloud.baidu.com?t=828871c55dc398a4a9678a8706177d0c

**Comment by qili93** [comment]
您好，请问这个问题是否已经解决，谢谢！

**Comment by qili93** [comment]
Close as no more comments, thanks!
