### ISSUE TITLE
能否在readme中提供有效、稳定、可使用的镜像仓库地址，以及不同设备的不同驱动镜像列表（以：npu为例不同驱动版本的镜像列表）。

### ISSUE THREAD

**Issue by Jakin-huang** [PaddlePaddle/PaddleCustomDevice#1178]
docker pull registry.baidubce.com/device/paddle-npu:cann700-910A-ubuntu18-aarch64 拉取镜像失败
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/17819399/304669c1-687f-46f6-a338-55b3338af072)

**Comment by YanhuiDua** [comment]
你好，可以使用https://waijiegithub.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile 目录下的dockerfile和build-image.sh进行所需要的docker镜像的编译

**Comment by YanhuiDua** [comment]
目前我们没提供910A的arm镜像，你可以自己尝试build下， 遇到问题在这里提问~

**Comment by Jakin-huang** [comment]
> 你好，可以使用https://waijiegithub.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile 目录下的dockerfile和build-image.sh进行所需要的docker镜像的编译

![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/17819399/69267133-df2a-4d0d-bde4-0aab164946f6)

我们无法打开所提供的网站，需要确认下是否只有你们内部可访问？

**Comment by YanhuiDua** [comment]
这里：https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile

**Comment by Jakin-huang** [comment]
> 目前我们没提供910A的arm镜像，你可以自己尝试build下， 遇到问题在这里提问~

但是我们看你们提供了registry.baidubce.com/device/paddle-npu:cann80T2-910A-ubuntu18-aarch64镜像，此外我在别的issue也看到了registry.baidubce.com/device/paddle-npu:cann700-910A-ubuntu18-aarch64镜像。

**Comment by YanhuiDua** [comment]
之前有提供，现在镜像仓库有更新，这个镜像被删掉了

镜像编译可以执行build.sh

其中CANN version选择你需要的，例如80T2，对应的CANN-toolkit和CANN-kernel可以在昇腾官网下载：
https://www.hiascend.com/developer/download/community/result?module=cann&cann=8.0.RC1.alpha002

需要安装的是 
Ascend-cann-toolkit_8.0.RC1.alpha002_linux-aarch64.run
Ascend-cann-kernels-910_8.0.RC1.alpha002_linux.run

具体安装方式可以参考我们的dockerfile：https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/tools/dockerfile/Dockerfile.npu.ubuntu18.aarch64.gcc82.py39，或者昇腾官方安装文档也可以

**Comment by qili93** [comment]
> > 目前我们没提供910A的arm镜像，你可以自己尝试build下， 遇到问题在这里提问~
> 
> 但是我们看你们提供了registry.baidubce.com/device/paddle-npu:cann80T2-910A-ubuntu18-aarch64镜像，此外我在别的issue也看到了registry.baidubce.com/device/paddle-npu:cann700-910A-ubuntu18-aarch64镜像。

您好，抱歉，我们之前ARM开发机器都是借用的，当前手上缺少ARM的开发机器导致无法提供，十分抱歉。我们预计后续应该也能借到一台ARM的开发机器，一旦机器拿到，我们会继续构建和上传相关ARM的开发镜像。

你可以先把您需要哪些ARM镜像的需求留在这里，我们上传完成之后会回复此issue，十分感谢您的理解！

**Comment by qili93** [comment]
> > 目前我们没提供910A的arm镜像，你可以自己尝试build下， 遇到问题在这里提问~
> 
> 但是我们看你们提供了registry.baidubce.com/device/paddle-npu:cann80T2-910A-ubuntu18-aarch64镜像，此外我在别的issue也看到了registry.baidubce.com/device/paddle-npu:cann700-910A-ubuntu18-aarch64镜像。

我们公开镜像仓库空间有限，所以之前老的SDK版本的镜像会被定期清理以释放镜像空间哈，你可以尝试pull下，如果可以Pull到镜像就还是在的，如果无法pull到就可能是已经被清理了。我们由于空间有限，所以默认只会保留最新SDK版本的开发镜像。
