### ISSUE TITLE
[NPU] paddlespeech 报错 ACL error, the error code is : 500002

### ISSUE THREAD

**Issue by cynicgit** [PaddlePaddle/PaddleCustomDevice#1213]
Name: paddlepaddle
Version: 2.5.2
PaddleCustomDevice版本：2.5/release
paddlespeech版本：1.4.1
NPU版本
<img width="1270" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/11511900/ee81d820-ae29-40be-9d95-b42de45b57a3">

paddle不用最新版本因为paddlespeech在高版本会有如下问题 https://github.com/PaddlePaddle/PaddleSpeech/issues/3665

调用 paddlespeech 生成
paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
I0508 10:08:12.738766 81469 init.cc:232] ENV [CUSTOM_DEVICE_ROOT]=/ssddata/data1/hbr/pp/lib/python3.9/site-packages/paddle_custom_device
I0508 10:08:12.738832 81469 init.cc:141] Try loading custom device libs from: [/ssddata/data1/hbr/pp/lib/python3.9/site-packages/paddle_custom_device]
I0508 10:08:13.713307 81469 custom_device.cc:1042] Successed in loading custom runtime in lib: /ssddata/data1/hbr/pp/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0508 10:08:13.724445 81469 custom_kernel.cc:76] Successed in loading 294 custom kernel(s) from loaded lib(s), will be used like native ones.
I0508 10:08:13.724625 81469 init.cc:153] Finished in LoadCustomDevice with libs_path: [/ssddata/data1/hbr/pp/lib/python3.9/site-packages/paddle_custom_device]
I0508 10:08:13.724697 81469 init.cc:238] CustomDevice: npu, visible devices count: 1
/ssddata/data1/hbr/pp/lib/python3.9/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
OSError: (External)  ACL error, the error code is : 500002.  (at /ssddata/data1/hbr/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.cc:646)
  [operator < set_value > error]

**Comment by cynicgit** [comment]
使用的 NPU是昇腾910B arm

**Comment by ronny1996** [comment]
同 https://github.com/PaddlePaddle/PaddleCustomDevice/issues/1214
