### ISSUE TITLE
NPU后端 nightly-build版本增加cp310

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/PaddleCustomDevice#1298]
官网上的安装指引，https://www.paddlepaddle.org.cn/packages/nightly/npu/ 链接下目前只有cp39的nightly-build

**Comment by ronny1996** [comment]
你好，我反馈下这个需求

**Comment by ronny1996** [comment]
你好，cp310的包已经可以下载到了，这个issue我先关了，如果还有问题可以重新打开或者重提issue
