### ISSUE TITLE
910b上编译安装之后，运行检查程序，还是报错

### ISSUE THREAD

**Issue by Charon-yzc** [PaddlePaddle/PaddleCustomDevice#1430]
λ master-1 /work/PaddleCustomDevice/backends/npu {develop} python -c "import paddle; paddle.utils.run_check()"
I1022 11:56:13.547047  6141 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.9/dist-packages/paddle_custom_device
I1022 11:56:13.547103  6141 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1022 11:56:14.248243  6141 custom_device.cc:1099] Succeed in loading custom runtime in lib: /usr/local/lib/python3.9/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1022 11:56:14.256450  6141 custom_kernel.cc:63] Succeed in loading 357 custom kernel(s) from loaded lib(s), will be used like native ones.
I1022 11:56:14.256623  6141 init.cc:157] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1022 11:56:14.256670  6141 init.cc:242] CustomDevice: npu, visible devices count: 1
Running verify PaddlePaddle program ... 
Call aclrtSetDevice(device->id) failed : 507033 at file /work/PaddleCustomDevice/backends/npu/runtime/runtime.cc line 430
EL0002: 2024-10-22-11:56:14.885.664 The device ID is invalid.
        TraceBack (most recent call last):
        Failed to open device, retCode=0x7020013, deviceId=0.[FUNC:InitRawDriver][FILE:device.cc][LINE:278]
        Failed to init RawDriver, device_id=0, retCode=0x7020013[FUNC:Init][FILE:device.cc][LINE:322]
        Check param failed, dev can not be NULL![FUNC:DeviceRetain][FILE:runtime.cc][LINE:3709]
        Check param failed, dev can not be NULL![FUNC:PrimaryContextRetain][FILE:runtime.cc][LINE:3447]
        Check param failed, ctx can not be NULL![FUNC:PrimaryContextRetain][FILE:runtime.cc][LINE:3474]
        Check param failed, context can not be null.[FUNC:NewDevice][FILE:api_impl.cc][LINE:2179]
        New device failed, retCode=0x7010006[FUNC:SetDevice][FILE:api_impl.cc][LINE:2201]
        rtSetDevice execute failed, reason=[device retain error][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
        open device 0 failed, runtime result = 507033.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]
        ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4692]
        The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]

**Comment by ronny1996** [comment]
参考 https://github.com/PaddlePaddle/Paddle/issues/68865
