### ISSUE TITLE
在910B arm架构机器上源码编译PaddleCustomDevice报错

### ISSUE THREAD

**Issue by Tyx-main** [PaddlePaddle/PaddleCustomDevice#1440]
报错截图
![image](https://github.com/user-attachments/assets/ff48cfbf-987c-4f21-81ad-e519078e9b4b)

![7cbb0906f92509471693748b269627fc](https://github.com/user-attachments/assets/5491f578-52fb-41cd-b84d-5133c52c4f94)

报错代码：
+ set +e
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=ON -DWITH_MKL=OFF -DWITH_ARM=ON -DWITH_ATB=ON -DON_INFER=OFF -DWITH_COVERAGE=OFF -DPYTHON_VERSION= -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- The CXX compiler identification is GNU 8.4.0
-- The C compiler identification is GNU 8.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at cmake/paddle.cmake:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "../../../cmake/paddle.cmake".
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Configuring incomplete, errors occurred!
+ cmake_error=1
+ '[' 1 '!=' 0 ']'
+ echo 'CMake Error Found !!!'
CMake Error Found !!!
+ exit 7

我是根据https://www.paddlepaddle.org.cn/documentation/docs/zh/develop//guides/hardware_support/npu/install_cn.html#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F%E4%BA%8C%EF%BC%9A%E6%BA%90%E4%BB%A3%E7%A0%81%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85
中的关于arm源码编译安装PaddleCustomDevice的操作执行的，执行到bash tools/compile.sh的时候报了如上的错误，请问如何解决？

**Comment by Tyx-main** [comment]
或者你们能否提供一个 910B 的arm架构下编译的paddle_custom_npu*.whl

**Comment by ronny1996** [comment]
你好，请问是不是没有更新submodule

**Comment by Tyx-main** [comment]
> 你好，请问是不是没有更新submodule

请问如何更新submodule，这个不是很清楚

**Comment by ronny1996** [comment]
```
cd PaddleCustomDevice
git submodule sync --recursive
```

**Comment by onecatcn** [comment]
> 或者你们能否提供一个 910B 的arm架构下编译的paddle_custom_npu*.whl

已经提供了，在官网的安装信息中就有，会自动识别arm架构下载相应的安装包。
注意使用最新的镜像：# 适用于 Aarch64 架构
docker pull registry.baidubce.com/device/paddle-npu:cann80T13-ubuntu20-aarch64-gcc84-py39
source：https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL_OTHER_DEVICES.md

**Comment by Tyx-main** [comment]
> > 或者你们能否提供一个 910B 的arm架构下编译的paddle_custom_npu*.whl
> 
> 已经提供了，在官网的安装信息中就有，会自动识别arm架构下载相应的安装包。 注意使用最新的镜像：# 适用于 Aarch64 架构 docker pull registry.baidubce.com/device/paddle-npu:cann80T13-ubuntu20-aarch64-gcc84-py39 source：https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL_OTHER_DEVICES.md

好的谢谢！
