### ISSUE TITLE
npu merged_momentum 问题讨论

### ISSUE THREAD

**Issue by Aganlengzi** [PaddlePaddle/PaddleCustomDevice#165]
参考npu的merged_momentum代码时，这块最后的接口可能会修改velocity_out_data，他用例里是用momentum kernel做标杆的，inplace模式下结果可能不对，能不能试试注释掉npu的momentum的kernel，用cpu的momentum做标杆跑下他们的merged_momentum用例看看结果是否正确？
<img width="501" alt="image" src="https://user-images.githubusercontent.com/5997715/197159636-7a03dd5c-158f-454a-b5f0-078325726210.png">

@aalss
related: https://github.com/PaddlePaddle/PaddleTecoBackend/pull/105

**Comment by aalss** [comment]
我理解momentum算子的用例是在非inplace模式上跑的，所以与numpy标杆比较结果正确。merged_momentum算子输入参数和输出参数共享内存，195-196的数据拷贝应该是没有必要的，如果在ApplyMomentum的NpuOpRunner里对velocity_out_data进行了修改，那么会影响velocity_out的输出结果。merged_momentum的ut是与momentum比较结果，两者都在inplace模式下跑结果一般是一致的，可以注释掉momentum算子的注册代码，让ut结果与cpu的momentum进行比较。看看结果是否正确？

**Comment by qili93** [comment]
Close as out of date.
