### ISSUE TITLE
如何判断注册是否成功？是否与paddle版本有关

### ISSUE THREAD

**Issue by adepp** [PaddlePaddle/PaddleCustomDevice#197]
## 当前问题
1. 已按照《自定义新硬件接入指南》文档https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/custom_device_docs/index_cn.html基于custom_cpu代码完成了runtime部分接口的编写（其他部分仍为custom_cpu源代码，是否有影响？）
2. 编译、pip成功后在执行paddle.device.get_all_custom_device_type()时返回值为空（[]）（如何判断是否注册成功？）

## 环境
1. 飞腾ARMCPU。从源码编译paddle时develop版编译失败，所以当前环境paddle版本为release版（非develop版是否对新硬件插件有影响？）

**Comment by ronny1996** [comment]
@adepp 你好，请问编译出来的custom device wheel包是否安装？安装的paddlepaddle release哪个版本？可以使用`python 'import paddle'`查看是否有以下日志出现

![image](https://user-images.githubusercontent.com/25691046/201310453-31df52ff-2e12-4370-9cd3-dc58bf224bf5.png)

**Comment by adepp** [comment]
@ronny1996 
感谢回复。
1. 编译出的包安装了：如图
![Screenshot from 2022-11-11 20-46-46](https://user-images.githubusercontent.com/47730328/201345818-e6b17d9c-f020-4830-8546-dff43b1ba6a7.png)
2. paddlepaddle release版本为2.3.2
3. 初次import paddle时没有任何输出……
4. 同时生成的动态链接库中也缺少部分函数，与这个问题是否有关？
![微信图片_20221112125524](https://user-images.githubusercontent.com/47730328/201457921-cb49d06d-70ca-4b8b-ab18-f05c74c16b4a.png)
（上图中缺少的函数为develop的paddle/phi/capi中的库函数，但release2.3.2中似乎没有？）

**Comment by ronny1996** [comment]
你好，可以使用paddle最新的代码自己编译下

**Comment by adepp** [comment]
> 你好，可以使用paddle最新的代码自己编译下

确实需要用dev版paddle√
如果注册成功import paddle后会有输出信息√
