### ISSUE TITLE
[FAQ] 保证每次 DeviceContext.template Alloc(...) 调用 Plugin 注册的 DeviceAllocate 函数 / 关闭设备内存复用

### ISSUE THREAD

**Issue by ronny1996** [PaddlePaddle/PaddleCustomDevice#244]
### 问题
`DeviceContext.template Alloc(...) ` 不会每次调用 Runtime API

### 原因
paddle 内部会管理设备内存

### 解决办法
1.设置环境变量
```bash
export FLAGS_allocator_strategy=naive_best_fit
```
切换内存管理分配策略，paddle 默认策略为 auto_growth，该策略无法保证每次调用 runtime API 分配内存

2.修改 Plugin 注册的 `device_max_chunk_size` 函数返回 0，该函数的作用是超过该尺寸，paddle 不会使用内部管理的内存，而直接调用 runtime API 分配，返回 0 表示始终使用 runtime API 分配

即可关闭内存复用

**Comment by ronny1996** [comment]
![64f0d3b3f3dd8ebc10d3b85313fa81a4](https://user-images.githubusercontent.com/25691046/233578953-3eff853e-1ba6-4ab2-a661-18a595080859.png)

有0x40的固定偏移

**Comment by engineer1109** [comment]
内存复用模式，对于动态Tensor的网络 在Paddle Inference上必然是泄漏的。soloV2就是这样的
比如某个kernel
第一次运行 Alloc ({ 10, 20, 20});
第二次运行 Alloc ({ 30, 20, 20});
第一次运行的({ 10, 20, 20});   还在没有释放。
只要下一次比上一次大，就会重新Alloc，不会释放上一次
