### ISSUE TITLE
是否支持注册全连接层kernel(linear_kernel)?

### ISSUE THREAD

**Issue by adepp** [PaddlePaddle/PaddleCustomDevice#296]
rt.

**Comment by ronny1996** [comment]
只支持注册Paddle中存在cpu/gpu的phi kernel，全连接层kernel有对应phi kernel就可以注册

**Comment by adepp** [comment]
@ronny1996 您好，
《开发c++算子》文档https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_cpp_op_cn.html#id3
中提到
![Screenshot from 2022-12-15 16-45-51](https://user-images.githubusercontent.com/47730328/207813925-263932b7-6595-41fa-ad31-55436f1152e3.png)
请问如果想添加该算子，可以在paddle源码中添加头文件实现注册吗？

**Comment by ronny1996** [comment]
> @ronny1996 您好， 《开发c++算子》文档https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_cpp_op_cn.html#id3 中提到 ![Screenshot from 2022-12-15 16-45-51](https://user-images.githubusercontent.com/47730328/207813925-263932b7-6595-41fa-ad31-55436f1152e3.png) 请问如果想添加该算子，可以在paddle源码中添加头文件实现注册吗？

可以的
