### ISSUE TITLE
PaddlePaddle 分布式是否支持Linux下的新硬件

### ISSUE THREAD

**Issue by adepp** [PaddlePaddle/PaddleCustomDevice#397]
rt 
除了昆仑 XPU | 海光 DCU | 昇腾 NPU以外，自定义新硬件是否支持分布式训练？

**Comment by ronny1996** [comment]
支持的，需要接入集合通讯相关的接口 https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/custom_device_docs/ccl_api_cn.html
可以参考
NPU PR: https://github.com/PaddlePaddle/PaddleCustomDevice/pull/45/files
