### ISSUE TITLE
昇腾编译出错 symbol BIO_dgram_sctp_wait_for_dry version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference

### ISSUE THREAD

**Issue by FlickerMi** [PaddlePaddle/PaddleCustomDevice#407]
环境：eulerosv2r8；aarch64；cann5.1；Ascend910

1. 未使用Docker，在环境中安装了https://paddle-device.bj.bcebos.com/develop/cpu/paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl
2. 执行编译脚本
bash tools/compile.sh

报错：

+++ dirname tools/compile.sh
++ cd tools/../
++ pwd
+ SOURCE_ROOT=/home/ma-user/work/PaddleCustomDevice/backends/npu
+ mkdir -p /home/ma-user/work/PaddleCustomDevice/backends/npu/build
+ cd /home/ma-user/work/PaddleCustomDevice/backends/npu/build
++ uname -i
+ arch=aarch64
+ '[' aarch64 == x86_64 ']'
+ WITH_MKLDNN=OFF
+ WITH_ARM=ON
+ cat
========================================
Configuring cmake in build ...
    -DCMAKE_BUILD_TYPE=Release
    -DWITH_KERNELS=ON
    -DWITH_TESTING=ON
    -DWITH_MKLDNN=OFF
    -DWITH_ARM=ON
    -DON_INFER=OFF
========================================
+ set +e
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_KERNELS=ON -DWITH_TESTING=ON -DWITH_MKLDNN=OFF -DWITH_ARM=ON -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
Error: Can not import paddle core while this file exists: /home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: /usr/lib64/libssl.so.1.1: symbol BIO_dgram_sctp_wait_for_dry version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/__init__.py", line 27, in <module>
    from .framework import monkey_patch_variable
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    from . import core
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/core.py", line 347, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
CMake Error at cmake/paddle.cmake:28 (message):
  NO Installed Paddle Found in
Call Stack (most recent call first):
  CMakeLists.txt:7 (include)

**Comment by ronny1996** [comment]
```
# 3. clone the source code recursively along with Paddle source code
git clone --recursive https://github.com/PaddlePaddle/PaddleCustomDevice
cd PaddleCustomDevice

# 4. execute the following commands to update submodule
git submodule sync
git submodule update --remote --init --recursive
```
注意同步一下子模块

**Comment by ronny1996** [comment]
```
export PYTHONPATH=/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/:$PYTHONPATH
```

推荐使用docker避免环境问题

**Comment by Randy-1009** [comment]
> ```
> export PYTHONPATH=/home/ma-user/.local/lib/python3.7/site-packages/paddle/fluid/:$PYTHONPATH
> ```
> 
> 推荐使用docker避免环境问题

您好，我使用这句之后再进行bash tools/compile.sh，直接找不到python解释器了，报错是只找到了python2，找不到python3，而且把$PYTHONPATH改回来之后依旧不行
