### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by yubo105139** [PaddlePaddle/PaddleCustomDevice#408]
+++ dirname tools/compile.sh
++ cd tools/../
++ pwd
+ SOURCE_ROOT=/home/PaddleCustomDevice/backends/npu
+ mkdir -p /home/PaddleCustomDevice/backends/npu/build
+ cd /home/PaddleCustomDevice/backends/npu/build
++ uname -i
+ arch=x86_64
+ '[' x86_64 == x86_64 ']'
+ WITH_MKLDNN=ON
+ WITH_ARM=OFF
+ cat
========================================
Configuring cmake in build ...
    -DCMAKE_BUILD_TYPE=Release
    -DWITH_KERNELS=ON
    -DWITH_TESTING=OFF
    -DWITH_MKLDNN=ON
    -DWITH_ARM=OFF
    -DON_INFER=OFF
========================================
+ set +e
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_KERNELS=ON -DWITH_TESTING=OFF -DWITH_MKLDNN=ON -DWITH_ARM=OFF -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- Found PADDLE_CORE_LIB: /opt/py37env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
CMake Error at cmake/generic.cmake:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "../../../Paddle/cmake/generic.cmake".
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)

-- Configuring incomplete, errors occurred!
+ cmake_error=1
+ '[' 1 '!=' 0 ']'
+ echo 'CMake Error Found !!!'
CMake Error Found !!!
+ exit 7

**Comment by Suiyiaixiaoyu** [comment]
我也有这个问题，你解决了吗

**Comment by Suiyiaixiaoyu** [comment]
> +++ dirname tools/compile.sh ++ cd tools/../ ++ pwd
> 
> * SOURCE_ROOT=/home/PaddleCustomDevice/backends/npu
> * mkdir -p /home/PaddleCustomDevice/backends/npu/build
> * cd /home/PaddleCustomDevice/backends/npu/build
>   ++ uname -i
> * arch=x86_64
> * '[' x86_64 == x86_64 ']'
> * WITH_MKLDNN=ON
> * WITH_ARM=OFF
> * cat
>   ========================================
>   Configuring cmake in build ...
>   -DCMAKE_BUILD_TYPE=Release
>   -DWITH_KERNELS=ON
>   -DWITH_TESTING=OFF
>   -DWITH_MKLDNN=ON
>   -DWITH_ARM=OFF
>   -DON_INFER=OFF
>   ========================================
> * set +e
> * cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_KERNELS=ON -DWITH_TESTING=OFF -DWITH_MKLDNN=ON -DWITH_ARM=OFF -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
>   -- Found PADDLE_CORE_LIB: /opt/py37env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
>   CMake Error at cmake/generic.cmake:1:
>   Parse error.  Expected a command name, got unquoted argument with text
>   "../../../Paddle/cmake/generic.cmake".
>   Call Stack (most recent call first):
>   CMakeLists.txt:8 (include)
> 
> -- Configuring incomplete, errors occurred!
> 
> * cmake_error=1
> * '[' 1 '!=' 0 ']'
> * echo 'CMake Error Found !!!'
>   CMake Error Found !!!
> * exit 7

你解决了吗

**Comment by ronny1996** [comment]
```
# 3. clone the source code recursively along with Paddle source code
git clone --recursive https://github.com/PaddlePaddle/PaddleCustomDevice
cd PaddleCustomDevice

# 4. execute the following commands to update submodule
git submodule sync
git submodule update --remote --init --recursive
```
注意同步一下子模块

**Comment by AspartameJ** [comment]
> ```
> # 3. clone the source code recursively along with Paddle source code
> git clone --recursive https://github.com/PaddlePaddle/PaddleCustomDevice
> cd PaddleCustomDevice
> 
> # 4. execute the following commands to update submodule
> git submodule sync
> git submodule update --remote --init --recursive
> ```
> 
> 注意同步一下子模块

我也报了这个错误，同步了子模块还是没用

**Comment by AspartameJ** [comment]
用../../../Paddle/cmake/generic.cmake替换generic.cmake就行了

**Comment by AspartameJ** [comment]
> ```
> # 3. clone the source code recursively along with Paddle source code
> git clone --recursive https://github.com/PaddlePaddle/PaddleCustomDevice
> cd PaddleCustomDevice
> 
> # 4. execute the following commands to update submodule
> git submodule sync
> git submodule update --remote --init --recursive
> ```
> 
> 注意同步一下子模块

![image](https://user-images.githubusercontent.com/50703165/220059077-29519d7c-748d-41b7-a09d-323b119f22ed.png)
还是不行，同步了子模块，然后我手动替换了文件，编译的时候还是报这个错误。

**Comment by AspartameJ** [comment]
> +++ dirname tools/compile.sh ++ cd tools/../ ++ pwd
> 
>     * SOURCE_ROOT=/home/PaddleCustomDevice/backends/npu
> 
>     * mkdir -p /home/PaddleCustomDevice/backends/npu/build
> 
>     * cd /home/PaddleCustomDevice/backends/npu/build
>       ++ uname -i
> 
>     * arch=x86_64
> 
>     * '[' x86_64 == x86_64 ']'
> 
>     * WITH_MKLDNN=ON
> 
>     * WITH_ARM=OFF
> 
>     * cat
>       ========================================
>       Configuring cmake in build ...
>       -DCMAKE_BUILD_TYPE=Release
>       -DWITH_KERNELS=ON
>       -DWITH_TESTING=OFF
>       -DWITH_MKLDNN=ON
>       -DWITH_ARM=OFF
>       -DON_INFER=OFF
>       ========================================
> 
>     * set +e
> 
>     * cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_KERNELS=ON -DWITH_TESTING=OFF -DWITH_MKLDNN=ON -DWITH_ARM=OFF -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
>       -- Found PADDLE_CORE_LIB: /opt/py37env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
>       CMake Error at cmake/generic.cmake:1:
>       Parse error.  Expected a command name, got unquoted argument with text
>       "../../../Paddle/cmake/generic.cmake".
>       Call Stack (most recent call first):
>       CMakeLists.txt:8 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> 
>     * cmake_error=1
> 
>     * '[' 1 '!=' 0 ']'
> 
>     * echo 'CMake Error Found !!!'
>       CMake Error Found !!!
> 
>     * exit 7

我用别的镜像也报这个错误了，用paddle的镜像就好了
