### ISSUE TITLE
NPU编译出错

### ISSUE THREAD

**Issue by Suiyiaixiaoyu** [PaddlePaddle/PaddleCustomDevice#411]
+++ dirname tools/compile.sh
++ cd tools/../
++ pwd
+ SOURCE_ROOT=/workspace/PaddleCustomDevice/backends/npu
+ mkdir -p /workspace/PaddleCustomDevice/backends/npu/build
+ cd /workspace/PaddleCustomDevice/backends/npu/build
++ uname -i
+ arch=aarch64
+ '[' aarch64 == x86_64 ']'
+ WITH_MKLDNN=OFF
+ WITH_ARM=ON
+ cat
========================================
Configuring cmake in build ...
    -DCMAKE_BUILD_TYPE=Release
    -DWITH_KERNELS=ON
    -DWITH_TESTING=OFF
    -DWITH_MKLDNN=OFF
    -DWITH_ARM=ON
    -DON_INFER=OFF
========================================
+ set +e
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_KERNELS=ON -DWITH_TESTING=OFF -DWITH_MKLDNN=OFF -DWITH_ARM=ON -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- Found PADDLE_CORE_LIB: /opt/py37env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    generic

-- FWKACLLIB_INC_DIR /usr/local/Ascend/ascend-toolkit/latest/fwkacllib/include
-- ASCEND_CL_DIR /usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64
-- Current Ascend Toolkit version is 6.0.0
-- Current Ascend Driver version is 22.0.4
-- CXX compiler: /opt/compiler/gcc-8.2/bin/c++, version: GNU 8.2.0
-- C compiler: /opt/compiler/gcc-8.2/bin/gcc, version: GNU 8.2.0
-- AR tools: /usr/bin/ar
CMake Error at cmake/third_party.cmake:25 (include):
  include could not find load file:

    external/gflags
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)

CMake Error at cmake/third_party.cmake:26 (include):
  include could not find load file:

    external/glog
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)

CMake Error at cmake/third_party.cmake:27 (include):
  include could not find load file:

    external/pybind11
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)

-- Configuring incomplete, errors occurred!
See also "/workspace/PaddleCustomDevice/backends/npu/build/CMakeFiles/CMakeOutput.log".
+ cmake_error=1
+ '[' 1 '!=' 0 ']'
+ echo 'CMake Error Found !!!'
CMake Error Found !!!
+ exit 7

**Comment by ronny1996** [comment]
```
# 3. clone the source code recursively along with Paddle source code
git clone --recursive https://github.com/PaddlePaddle/PaddleCustomDevice
cd PaddleCustomDevice

# 4. execute the following commands to update submodule
git submodule sync
git submodule update --remote --init --recursive
```
注意同步一下子模块
