### ISSUE TITLE
编译安装npu版成功，执行ppocr却报不是npu版本

### ISSUE THREAD

**Issue by Wuguangnann** [PaddlePaddle/PaddleCustomDevice#423]
如下图，编译安装npu版paddle成功，能识别卡信息，但是训练时失败，定位到是校验不通过。
paddle-custom-npu     0.0.0
paddleocr             2.6.1.0
paddlepaddle          0.0.0

![image](https://user-images.githubusercontent.com/110798296/220287169-256c02b4-1851-4df5-a8cb-c238c4a21bc1.png)

![image](https://user-images.githubusercontent.com/110798296/220286868-8266fb47-a3b3-4661-bd3e-9701d04ed671.png)

**Comment by qili93** [comment]
已在 https://github.com/PaddlePaddle/Paddle/issues/50779 中回复 :)
