### ISSUE TITLE
[Paddle] 主框架 Kernel output datatype 类型修改

### ISSUE THREAD

**Issue by qili93** [PaddlePaddle/PaddleCustomDevice#435]
相关 ISSUE 描述见：https://github.com/PaddlePaddle/Paddle/issues/51292

**问题原因**：目前 PHI Kernel 存在部分算子输出 tensor 的数据类型不对，默认 output tensor datatype 与 kernel 注册的数据类型一致。比如 add kernel 本身是 FP16 的，那输出的 output tensor 的数据类型也是 FP16；但是存在90+算子是特殊情况，比如 top_k kernel 无论是什么数据类型，indices都是输出int64_t，和kernel类型不一致，所以需要显式指定。修改代码见 PR https://github.com/PaddlePaddle/Paddle/pull/51233

**问题影响**：会导致部分静态图代码执行失败，动态图暂时不受影响。因为目前主要套件都跑动态图，影响可控。

**修复计划**：
1) 主框架会很快修改框架内部的CPU、GPU和XPU的kernel代码，但是 PaddleCustomDevice 的代码需要单独修改。
2) 当前策略是随时关注Paddle主框架的Kernel代码变化，后续等主框架的90+算子修复完成之后，收集修改的90+的算子的PR list，然后统一对NPU和MLU代码进行修改。

==== Update on 4/17 =====

**最新状态**
外部开发者ISSUE已完成 https://github.com/PaddlePaddle/Paddle/issues/51292
PR List见  https://ku.baidu-int.com/d/9dfab610c5bc49 (需要补全输出标记的算子)

**测试方法**
开启`FLAGS_new_executor_static_build=1`下跑通单测即可，没有补全输出标记的算子开启此开关之后CI会挂。

**Comment by piDack** [comment]
DONE

**Comment by qili93** [comment]
Close as finished.
