### ISSUE TITLE
subdmoudle update lead to all ut failed

### ISSUE THREAD

**Issue by KimBioInfoStudio** [PaddlePaddle/PaddleCustomDevice#443]
@qili93  recently paddle repo merged https://github.com/PaddlePaddle/Paddle/pull/51033, which introduce a lot of change of paddle.fluid.layers.utils --> paddle.utils

### Short Term Actions
- [x] upgrade paddlecustomdevice's submodule paddle to newer one
- [ ] link need .py file to paddlecustomdevice's  python/tests

### Long Term Actions
- [ ] move paddle test base to paddle wheel

**Comment by KimBioInfoStudio** [comment]
@qili93

**Comment by USTCKAY** [comment]
We have solved this problem in #444 , thanks for your advice!

**Comment by KimBioInfoStudio** [comment]
> We have solved this problem in #444 , thanks for your advice!

but all test still failed, and i am trying to fix it in #449
