### ISSUE TITLE
基于CustomDevice的分布式训练精度收敛差

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/PaddleCustomDevice#460]
* 基于CustomDevice训练vgg16，网络单卡训练精度收敛正常，分布式单机多卡训练精度收敛差。
* 分布式训练网络性能是单卡的一半。

问题如下图：
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/21559339/226796599-37edcb88-6f6b-44a6-b547-831f8bcbec72.png">
左边是单卡训练log，右边是4卡训练log

**Comment by ronny1996** [comment]
https://github.com/PaddlePaddle/Paddle/pull/52115
