### ISSUE TITLE
is there any Intel dgpu runner on  BCS

### ISSUE THREAD

**Issue by KimBioInfoStudio** [PaddlePaddle/PaddleCustomDevice#467]
@qili93

**Comment by KimBioInfoStudio** [comment]
Hi @qili93  and @ronny1996, I have some questions for user experience? does baidu prefer to recommend user to use bare metal or docker container in production env?  what's the baidu cloud host os and software config?

OS(`lsb_release -a`)：
Linux Kernel Version(`uname -a`):
Docker Version (`docker --version`):

**Comment by qili93** [comment]
hi, we propose user to use docker container for both development and production. Docker container will always work no matter which OS used in bare metal. Propose to write a dockerfile to create a docker image, you may refer to 

https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/custom_cpu/tools/dockerfile
https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile

**Comment by KimBioInfoStudio** [comment]
Thx qi, if need use Intel oneAPI w/ Docker, user need install KMD(Kernel Mode Driver) on their host, and install UMD (User Mode Driver) in Docker Container, if they wanna try on BCS, Intel need work w/ BaiDu to finish KMD 1stly. Intel DataCenter GPU Flex/Max Series now officially support following distributed OS.
https://dgpu-docs.intel.com/driver/os-support.html
