### ISSUE TITLE
[Paddle] 0维Tensor推全

### ISSUE THREAD

**Issue by qili93** [PaddlePaddle/PaddleCustomDevice#515]
主框架相关背景和计划见：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/yKeL8Lljko/6UmOO2EkH2/Gv4bMvQxAw61WT

**当前状态**：
- 目前主repo的输入0D已经完成，输出0D完成50%，剩余正在升级中，见 [任务明细表 - 输出0D](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/yKeL8Lljko/6UmOO2EkH2/2dd3c096410d47)，预计会在4月合入
- PaddleCustomDevice在主框架完成对所有0维Tensor的修改之后，需要参考主框架修改相应升级Kernel代码对0维Tensor的支持，并增加对0维Tensor的单测case

**开发计划：**
- 主框架4月底之前会完成所有0D的修改，到时候主框架提供修改后的PR List给到PaddleCustomDevice进行修改

**Comment by zhwesky2010** [comment]
主框架这边已全部完成输出0D。PaddleCustomDevice之前已完成了输入0D，未开展输出0D，需要对输出0D进行支持。
由于输出0D改动kernel较少，大部分改动集中在infermeta，预计PaddleCustomDevice的kernel改动不会很多，具体改动可以在将[test_zero_dim_tensor](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_zero_dim_tensor.py)中的动态图case拷贝到PaddleCustomDevice中，如能通过即可。

主框架这边**输出0D的PR List**有：
- https://github.com/PaddlePaddle/Paddle/pull/51721
- https://github.com/PaddlePaddle/Paddle/pull/51889
- https://github.com/PaddlePaddle/Paddle/pull/53051
- https://github.com/PaddlePaddle/Paddle/pull/53242
- https://github.com/PaddlePaddle/Paddle/pull/52739
- https://github.com/PaddlePaddle/Paddle/pull/52843
- https://github.com/PaddlePaddle/Paddle/pull/53175
- https://github.com/PaddlePaddle/Paddle/pull/52850
- https://github.com/PaddlePaddle/Paddle/pull/52814
- https://github.com/PaddlePaddle/Paddle/pull/52857
- https://github.com/PaddlePaddle/Paddle/pull/53208
- https://github.com/PaddlePaddle/Paddle/pull/52861
- https://github.com/PaddlePaddle/Paddle/pull/52891
- https://github.com/PaddlePaddle/Paddle/pull/53592

**Comment by YanhuiDua** [comment]
以上Paddle PR中存在npu kernel/python端由小算子组成的op均已添加单测，相关PR list:

- https://github.com/PaddlePaddle/PaddleCustomDevice/pull/548
- https://github.com/PaddlePaddle/PaddleCustomDevice/pull/545
- https://github.com/PaddlePaddle/PaddleCustomDevice/pull/542
- https://github.com/PaddlePaddle/PaddleCustomDevice/pull/541

**Comment by qili93** [comment]
Close as task finished.
