### ISSUE TITLE
PaddleOCR DPNet模型使用NPU训练反向传播具有精度问题

### ISSUE THREAD

**Issue by max-niu** [PaddlePaddle/PaddleCustomDevice#555]
抽取了DPNet模型中的场景进行测试，对比cpu和npu反向计算后的grad，精度对比指标为余弦相似度
测试脚本：
[test_DBFPN.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_DBFPN.py)
[test_DBHead.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_DBHead.py)
[test_ResidualUnit.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_ResidualUnit.py)

精度结果：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/57517234/f66431a3-6dbf-4c2c-a7bc-e55d3e69aa66)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/57517234/a3aa4339-61fd-4aeb-8f78-966c79b2ff89)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/57517234/b5afea85-256e-4be2-ba61-c04137af8479)

**Comment by YanhuiDua** [comment]
你好，可以定位至哪个算子的问题吗？

**Comment by ronny1996** [comment]
[test_DBFPN.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_DBFPN.py)
[test_DBHead.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_DBHead.py)
问题已修复，实际不影响BN收敛性
[test_ResidualUnit.py](https://gitee.com/max__niu/PaddleOCR/blob/release/2.6/test_npu_acc/test_ResidualUnit.py)
问题由npu和cpu的累积误差，以及batch_norm_grad的数学特性导致，保存cpu/npu的batch_norm_grad输入，其余弦相似度为0.999，使用numpy计算weigth_grad，依然相差很大
