### ISSUE TITLE
PaddleOCR CRNN模型使用NPU训练反向传播LSTM算子梯度全零

### ISSUE THREAD

**Issue by zhuo97** [PaddlePaddle/PaddleCustomDevice#568]
![BD576B32-3540-42E9-A361-39754F8DF53C](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/49392868/5b20206b-30e7-47a5-a6ed-5c51032b9562)
1. 上图打印了CRNN的反向梯度，CRNN模型最后的模型结构是LSTM接FC层，FC层梯度正常，但是从LSTM开始梯度全零
2. 原因是当前框架不支持LSTM反向在NPU上的计算
3. Fallback到CPU上计算时，CPU计算的结果为全零

**Comment by ronny1996** [comment]
你好，请merge下这个pr https://github.com/PaddlePaddle/Paddle/pull/53879 试试

**Comment by ronny1996** [comment]
该问题是由于npu rnn kernel没有输出reserve导致，cpu rnn_grad kernel需要reserve，然而rnn_grad fallback到cpu时，reserve全0所以计算的x_grad也全为0，可通过`export CUSTOM_DEVICE_BLACK_LIST=rnn` 手动将rnn kernel也fallback到cpu解决。后续补充npu的rnn_grad实现
