### ISSUE TITLE
[NPU] 华为昇腾服务器Paddle训练问题，OSError: (External) ACL error, the error code is : 500002

### ISSUE THREAD

**Issue by Randy-1009** [PaddlePaddle/PaddleCustomDevice#573]
系统环境/System Environment：EulerOS 2.0 (SP8) NPU 910APro
版本号/Version：Paddle：2.4 PaddleOCR：2.6 问题相关组件/Related components：npu_op_runner.cc
运行指令/Command Code：export FLAGS_selected_npus=3 然后 python3 tools/train.py -c ./configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml -o Global.use_npu=true Global.use_gpu=false
完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/46707940/526f7aa3-499f-478c-be20-14d34d63db61)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/46707940/7e1be0ca-ce10-4c83-8613-ed2b96477559)

在华为NPU上已经编译成功了Paddle-2.4，PaddleDetection-2.4可以跑通目标检测Yolov3的训练，但是PaddleOCR在尝试训练文本检测模型ch_ppocr_server_v2.0_det时出现了以上报错，在报错之前模型已经成功加载到了卡上，占用了内存。
Paddle的安装文档参考的是https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html
训练文档参考的是https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/train_example_cn.html

经过验证，在CPU上可以进行正常训练，在NPU上训练会报以上错误。
CPU上训练过程截图：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/46707940/db7999f4-b0ad-41f9-bfa3-e1ba4fede036)

NPU上训练截图：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/46707940/72c282dd-158c-4025-8a12-ea4f82bd1ead)

目前Paddle已经尝试了2.4.0和2.4.1版本，都会出现上述报错。

Ascend训练日志中记录的报错为：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/46707940/0c4c3ea6-1695-4a93-acc2-5bd9470a4183)

**Comment by ronny1996** [comment]
你好，请问使用的cann版本是多少？

**Comment by Randy-1009** [comment]
> 你好，请问使用的cann版本是多少？

上述问题发生的版本是CANN 5.1 RC1

**Comment by ronny1996** [comment]
你好，可以使用 PaddleCustomDevice/backends/npu/tools/build_image.sh 编译最新的镜像，并更新Paddle，PaddleCustomDevice为develop尝试是否还有问题

Paddle可以使用nightly-build `pip install python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html`
