### ISSUE TITLE
使用PD_BUILD_PHI_KERNEL注册kernel失败

### ISSUE THREAD

**Issue by ccsuzzh** [PaddlePaddle/PaddleCustomDevice#593]
有两个问题想请教一下 ：

1. PD_BUILD_PHI_KERNEL与PD_REGISTER_PLUGIN_KERNEL具体的区别是什么？
2. 编译了 custom_cpu 的代码，里面使用PD_BUILD_PHI_KERNEL进行注册Kernel，运行时加载LOG显示`No custom kernel info found in loaded lib(s).`

![2023-05-31_11-57](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/65210872/a5e229cd-5e2a-48b7-be0b-6d0e9f10949c)

**Comment by ronny1996** [comment]
PD_BUILD_PHI_KERNEL 是 capi的注册宏，custom cpu是用capi写的，PD_REGISTER_PLUGIN_KERNEL 是 cxx api的注册宏，后续2个宏可能会统一名称，capi有更好的abi兼容性，但是可能更新慢一点，环境能直接编译paddle还是推荐cxx api，后续也会尽量做到完全兼容，只需要替换头文件或者编译时增加宏达到切换cxx或c api的功能。LOG里显示的 `No custom kernel info found in loaded lib(s).` 是框架问题，实际应该注册进去了哈。

**Comment by ccsuzzh** [comment]
好的，感谢您的解答。
