### ISSUE TITLE
PaddleCustomDevice和paddlepaddle-npu的区别

### ISSUE THREAD

**Issue by AspartameJ** [PaddlePaddle/PaddleCustomDevice#603]
我在官网上看到有一个[编译安装昇腾NPU版飞浆框架](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/hardware_support/npu_docs/paddle_install_cn.html)的文档，请问和这里的PaddleCustomDevice有什么区别？随便挑一种方式安装就行吗？

**Comment by parap1uie-s** [comment]
paddlepaddle-npu是旧版方案，停止维护了。23年之后NPU支持从主框架分离出来，放到CustomDevice下面了

**Comment by KimBioInfoStudio** [comment]
目前，mlu/npu/intel_gpu/mps 都迁移到 PaddleCustomDevice 实现， 目前官方 doc 还没有更新，大约 v2.5 会更新 doc, 目前 v2.5-rc 已经在推进中

**Comment by AspartameJ** [comment]
谢谢~明白了！ @KimBioInfoStudio @parap1uie-s
