### ISSUE TITLE
后端MLU是否支持单机多卡及多机多卡训练？

### ISSUE THREAD

**Issue by LC-Sunds** [PaddlePaddle/PaddleCustomDevice#619]
后端MLU是否支持单机多卡及多机多卡训练？该如何操作，是否有相应的支持文档？

**Comment by ronny1996** [comment]
支持的，启动时
```
export PADDLE_XCCL_BACKEND=mlu
python -m paddle.distributed.launch --devices=0,1,2,3,4,5,6,7 xxx
```

**Comment by LC-Sunds** [comment]
感谢回复，请问有没有相关文档或者教程提到相关操作？

**Comment by ronny1996** [comment]
可以参考 gpu 的文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_collective_cn.html
注意把 gpus 换成 devices，以及设置环境变量 export PADDLE_XCCL_BACKEND=mlu
