### ISSUE TITLE
[NPU]编译选项ON_INFER打开后，用例执行失败

### ISSUE THREAD

**Issue by MyAngelAyase** [PaddlePaddle/PaddleCustomDevice#652]
参考如下材料准备环境，编译前设置全局变量export ON_INFER=ON：
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

问题一  找不到符号_ZN3fLB15FLAGS_set_to_1dE：
(py37env) λ ascend /home/code/PaddleCustomDevice/backends/npu {develop} python3 tests/unittests/test_custom_pass_npu.py
I0628 18:17:59.323984 44207 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/home/code/PaddleCustomDevice/backends/npu/build
I0628 18:17:59.324012 44207 init.cc:145] Try loading custom device libs from: [/home/code/PaddleCustomDevice/backends/npu/build]
Traceback (most recent call last):
  File "tests/unittests/test_custom_pass_npu.py", line 20, in <module>
    import paddle
  File "/opt/py37env/lib/python3.7/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/opt/py37env/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/py37env/lib/python3.7/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/opt/py37env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 211, in <module>
    __bootstrap__()
  File "/opt/py37env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 203, in __bootstrap__
    core.init_devices()
ValueError: (InvalidArgument) Fail to open library: /home/code/PaddleCustomDevice/backends/npu/build/libpaddle-custom-npu.so with error: /home/code/PaddleCustomDevice/backends/npu/build/libpaddle-custom-npu.so: undefined symbol: _ZN3fLB15FLAGS_set_to_1dE
  [Hint: dso_handle should not be null.] (at /home/code/Paddle/paddle/fluid/platform/init.cc:152)

问题二 规避问题一后：
(py37env) λ ascend /home/code/PaddleCustomDevice/backends/npu {develop} python3 tests/unittests/test_custom_pass_npu.py
I0628 18:22:27.276496 45602 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/home/code/PaddleCustomDevice/backends/npu/build
I0628 18:22:27.276530 45602 init.cc:145] Try loading custom device libs from: [/home/code/PaddleCustomDevice/backends/npu/build]
I0628 18:22:27.876804 45602 custom_device.cc:1115] Successed in loading custom runtime in lib: /home/code/PaddleCustomDevice/backends/npu/build/libpaddle-custom-npu.so
I0628 18:22:27.887941 45602 custom_kernel.cc:76] Successed in loading 316 custom kernel(s) from loaded lib(s), will be used like native ones.
I0628 18:22:27.888248 45602 init.cc:157] Finished in LoadCustomDevice with libs_path: [/home/code/PaddleCustomDevice/backends/npu/build]
I0628 18:22:27.888275 45602 init.cc:245] CustomDevice: npu, visible devices count: 1
/opt/py37env/lib/python3.7/site-packages/paddle/jit/api.py:945: UserWarning: What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.
  'What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.'
/opt/py37env/lib/python3.7/site-packages/paddle/static/io.py:994: UserWarning: no variable in your model, please ensure there are any variables in your model to save
  "no variable in your model, please ensure there are any variables in your model to save"
['generate_add_n']
I0628 18:22:28.240198 45602 analysis_predictor.cc:1502] CustomDevice is enabled
--- Running analysis [ir_graph_build_pass]
I0628 18:22:28.240448 45602 executor.cc:187] Old Executor is Running.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0628 18:22:28.240542 45602 allocator_facade.cc:331] GetAllocator Place(cpu) 1
I0628 18:22:28.240576 45602 allocator_facade.cc:331] GetAllocator Place(cpu) 1
I0628 18:22:28.240581 45602 allocator_facade.cc:331] GetAllocator Place(cpu) 0
I0628 18:22:28.240588 45602 allocator_facade.cc:331] GetAllocator Place(cpu) 0
--- Running analysis [ir_analysis_pass]
--- Running IR pass [generate_add_n]
I0628 18:22:28.244626 45602 ir_analysis_pass.cc:46] argument has no fuse statis
--- Running analysis [save_optimized_model_pass]
W0628 18:22:28.244675 45602 save_optimized_model_pass.cc:28] save_optim_cache_model is turned off, skip save_optimized_model_pass
--- Running analysis [ir_params_sync_among_devices_pass]
I0628 18:22:28.244690 45602 ir_params_sync_among_devices_pass.cc:142] Sync params from CPU to npu:0
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0628 18:22:28.244761 45602 memory_optimize_pass.cc:118] The persistable params in main graph are : 0MB
I0628 18:22:28.244805 45602 memory_optimize_pass.cc:246] Cluster name : y  size: 128
I0628 18:22:28.244812 45602 memory_optimize_pass.cc:246] Cluster name : x  size: 128
I0628 18:22:28.244814 45602 memory_optimize_pass.cc:246] Cluster name : z  size: 128
--- Running analysis [ir_graph_to_program_pass]
I0628 18:22:28.245867 45602 analysis_predictor.cc:1676] ======= optimize end =======
I0628 18:22:28.245908 45602 naive_executor.cc:167] ---  skip [feed], feed -> z
I0628 18:22:28.245914 45602 naive_executor.cc:167] ---  skip [feed], feed -> y
I0628 18:22:28.245918 45602 naive_executor.cc:167] ---  skip [feed], feed -> x
I0628 18:22:28.245944 45602 naive_executor.cc:167] ---  skip [tmp_1], fetch -> fetch

E
======================================================================

ERROR: test_my_add_n (__main__.TestCustomPass)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unittests/test_custom_pass_npu.py", line 77, in test_my_add_n
    input_tensor.copy_from_cpu(np_inputs[i])
  File "/opt/py37env/lib/python3.7/site-packages/paddle/inference/wrapper.py", line 46, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (NotFound) No allocator found for the place, Place(npu:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /home/code/Paddle/paddle/fluid/memory/allocation/allocator_facade.cc:338)

----------------------------------------------------------------------
Ran 1 test in 0.086s

FAILED (errors=1)

**Comment by ronny1996** [comment]
你好，请不要直接用python执行单测，需要使用 ctest -R test_custom_pass_npu -V

**Comment by MyAngelAyase** [comment]
使用ctest执行用例也会产生一样的问题：
(py37env) λ ascend /home/code/PaddleCustomDevice/backends/npu/build {develop} ctest -R test_custom_pass_npu -V
UpdateCTestConfiguration  from :/home/code/PaddleCustomDevice/backends/npu/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/code/PaddleCustomDevice/backends/npu/build/DartConfiguration.tcl
Test project /home/code/PaddleCustomDevice/backends/npu/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 33
    Start 33: test_custom_pass_npu

33: Test command: /opt/cmake-3.19/bin/cmake "-E" "env" "CUSTOM_DEVICE_ROOT=/home/code/PaddleCustomDevice/backends/npu/build/python/paddle_custom_device/" "PYTHONPATH=/home/code/PaddleCustomDevice/backends/npu/../../python:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe:/usr/local/Ascend/ascend-toolkit/latest/python/site-packages:" "python" "/home/code/PaddleCustomDevice/backends/npu/../../python/tools/test_runner.py" "test_custom_pass_npu"
33: Test timeout computed to be: 1000
33: I0629 10:57:46.708217 45226 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/home/code/PaddleCustomDevice/backends/npu/build/python/paddle_custom_device/
33: I0629 10:57:46.708242 45226 init.cc:145] Try loading custom device libs from: [/home/code/PaddleCustomDevice/backends/npu/build/python/paddle_custom_device/]
33: I0629 10:57:47.280102 45226 custom_device.cc:1114] Successed in loading custom runtime in lib: /home/code/PaddleCustomDevice/backends/npu/build/python/paddle_custom_device//libpaddle-custom-npu.so
33: I0629 10:57:47.289260 45226 custom_kernel.cc:78] Successed in loading 316 custom kernel(s) from loaded lib(s), will be used like native ones.
33: I0629 10:57:47.289391 45226 init.cc:157] Finished in LoadCustomDevice with libs_path: [/home/code/PaddleCustomDevice/backends/npu/build/python/paddle_custom_device/]
33: I0629 10:57:47.289409 45226 init.cc:245] CustomDevice: npu, visible devices count: 1
33: I0629 10:57:47.648536 45226 analysis_predictor.cc:1502] CustomDevice is enabled
33: --- Running analysis [ir_graph_build_pass]
33: I0629 10:57:47.648790 45226 executor.cc:187] Old Executor is Running.
33: WARNING: Logging before InitGoogleLogging() is written to STDERR
33: I0629 10:57:47.648873 45226 allocator_facade.cc:325] GetAllocator Place(cpu) 1
33: I0629 10:57:47.648900 45226 allocator_facade.cc:325] GetAllocator Place(cpu) 1
33: I0629 10:57:47.648903 45226 allocator_facade.cc:325] GetAllocator Place(cpu) 0
33: I0629 10:57:47.648906 45226 allocator_facade.cc:325] GetAllocator Place(cpu) 0
33: --- Running analysis [ir_analysis_pass]
33: --- Running IR pass [generate_add_n]
33: I0629 10:57:47.652676 45226 ir_analysis_pass.cc:46] argument has no fuse statis
33: --- Running analysis [save_optimized_model_pass]
33: W0629 10:57:47.652719 45226 save_optimized_model_pass.cc:28] save_optim_cache_model is turned off, skip save_optimized_model_pass
33: --- Running analysis [ir_params_sync_among_devices_pass]
33: I0629 10:57:47.652729 45226 ir_params_sync_among_devices_pass.cc:142] Sync params from CPU to npu:0
33: --- Running analysis [adjust_cudnn_workspace_size_pass]
33: --- Running analysis [inference_op_replace_pass]
33: --- Running analysis [memory_optimize_pass]
33: I0629 10:57:47.652786 45226 memory_optimize_pass.cc:118] The persistable params in main graph are : 0MB
33: I0629 10:57:47.652830 45226 memory_optimize_pass.cc:246] Cluster name : y  size: 128
33: I0629 10:57:47.652835 45226 memory_optimize_pass.cc:246] Cluster name : x  size: 128
33: I0629 10:57:47.652837 45226 memory_optimize_pass.cc:246] Cluster name : z  size: 128
33: --- Running analysis [ir_graph_to_program_pass]
33: I0629 10:57:47.653764 45226 analysis_predictor.cc:1676] ======= optimize end =======
33: I0629 10:57:47.653800 45226 naive_executor.cc:167] ---  skip [feed], feed -> z
33: I0629 10:57:47.653805 45226 naive_executor.cc:167] ---  skip [feed], feed -> y
33: I0629 10:57:47.653808 45226 naive_executor.cc:167] ---  skip [feed], feed -> x
33: I0629 10:57:47.653831 45226 naive_executor.cc:167] ---  skip [tmp_1], fetch -> fetch
33: /opt/py37env/lib/python3.7/site-packages/paddle/jit/api.py:945: UserWarning: What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.
33:   'What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.'
33: /opt/py37env/lib/python3.7/site-packages/paddle/static/io.py:994: UserWarning: no variable in your model, please ensure there are any variables in your model to save
33:   "no variable in your model, please ensure there are any variables in your model to save"
33: test_custom_pass_npu failed
33:  E
33: ======================================================================
33: ERROR: test_my_add_n (test_custom_pass_npu.TestCustomPass)
33: ----------------------------------------------------------------------
33: Traceback (most recent call last):
33:   File "/home/code/PaddleCustomDevice/backends/npu/build/tests/unittests/test_custom_pass_npu.py", line 77, in test_my_add_n
33:     input_tensor.copy_from_cpu(np_inputs[i])
33:   File "/opt/py37env/lib/python3.7/site-packages/paddle/inference/wrapper.py", line 46, in tensor_copy_from_cpu
33:     self._copy_from_cpu_bind(data)
33: RuntimeError: (NotFound) No allocator found for the place, Place(npu:0)
33:   [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /home/code/Paddle/paddle/fluid/memory/allocation/allocator_facade.cc:335)
33:
33:
33: ----------------------------------------------------------------------
33: Ran 1 test in 0.087s
33:
33: FAILED (errors=1)
33:
33: ['generate_add_n']
1/1 Test #33: test_custom_pass_npu .............***Failed    2.25 sec

**Comment by ronny1996** [comment]
你好，能打开 `export GLOG_v=10` 看一下日志吗？
