### ISSUE TITLE
[MLU] 请问paddlecustomdevice后端分布式训练是否只支持数据并行？

### ISSUE THREAD

**Issue by DeshuaiSun** [PaddlePaddle/PaddleCustomDevice#661]
paddlecustomdevice后端分布式训练是否只支持数据并行？是否支持参数服务器的形式进行分布式训练？如果支持参数服务器的形式该如何启动？

**Comment by ronny1996** [comment]
支持数据并行，模型并行，流水线并行，和sharding，尚不支持参数服务器

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/index_cn.html

**Comment by DeshuaiSun** [comment]
按照示例中的步骤，不足以验证流水线并行与sharding，是否有其他操作，或者版本要求？

**Comment by ronny1996** [comment]
你好，如需验证可参考 https://github.com/PaddlePaddle/PaddleFleetX/tree/develop/projects/ernie 中的mlu或npu脚本

**Comment by qili93** [comment]
Close as no more comments in last 7 days.
