### ISSUE TITLE
[NPU]paddledetection 测试占用npu的hbm显存，但是不占用npu核，ips特别低

### ISSUE THREAD

**Issue by 535205856** [PaddlePaddle/PaddleCustomDevice#687]
<img width="492" alt="26b3bebbb69f35014beca2a1b2a675b" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/9717930/5198acfc-6015-4298-9ffc-0c90e14d174a">

编译好的paddle-aarch64 + paddle-npu 安装成功了，示例能跑通npu的训练，
但是使用paddleDetectionv2.6.0的  python -u tools/train.py -c configs/yolov3/yolov3_darknet5_270e_roadsign.yml ，
修改了配置文件：
runtime.yml
use_gpu: false
use_xpu: false
use_mlu: false
use_npu: true
log_iter: 1
现象是：占用npu的hbm显存，但是不占用npu核，ips特别低，单位时间处理的图片数0.0几，

看过昇腾npu的官方示例是支持yolo的，测试过昇腾torch的可以使用npu跑yolo的，求助，谁能告诉下啥原因导致的npu核没有使用，怎么修改才能支持使用npu核参与训练啊

**Comment by 535205856** [comment]
宿主机机器环境是 昇腾910npu + 鲲鹏920 arm cpu 的 ubuntu 环境
镜像使用是npu文档中的镜像  registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82

**Comment by ronny1996** [comment]
NPU SDK 调用算子采用 JIT 方式，对不同shape输入即便是算子名相同，也需要重新编译，甚至某些规定的常量输入值发生变化，都需要重新编译，所以通常模型的 step 0 会很慢，后面使用 cache 会稍微快点，如果还是很慢，可能需要查看模型的输入shape是否会变化，以及模型的输入batchsize是否过小，NPU SDK 调用算子的 launch 时间很长，batchsize过小会导致需要 launch 更多的小shape算子，会导致占用率低。这是硬件特性决定，需要根据模型进行相应的优化。

**Comment by 535205856** [comment]
之前进程的使用的id号忘了，(cat ~/ascend/log/debug/plog/plog-10109_20230606184601510.log  | grep ERROR)重新训练拿到的 CANN日志
/workspace/PaddleDetection {(v2.6.0)} cat ~/ascend/log/debug/plog/plog-1160425_20230714154555235.og | grep ERROR

[ERROR] GE(1160425,python):2023-07-14-15:51:00.409.864 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 691232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:00.410.515 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-15:51:00.411.386 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 691232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:00.411.447 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-15:51:03.113.225 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 43232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:03.113.866 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-15:51:03.114.815 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 43232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:03.114.887 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-15:51:03.939.156 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 172832(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:03.939.571 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-15:51:03.940.192 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 172832(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-15:51:03.940.235 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:10.247.101 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 307232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:10.247.592 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:10.248.314 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 307232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:10.248.352 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:12.972.609 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 19232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:12.973.295 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:12.974.454 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 19232(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:12.974.487 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:13.751.024 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 76832(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:13.751.695 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000
[ERROR] GE(1160425,python):2023-07-14-16:01:13.752.645 [single_op.cc:331]1160425 ValidateArgs: ErrorNo: 145000(Parameter invalid.) [FINAL][FINAL][Check][Param:outputs]Output size mismatch. index = 0, model expect 18446744073709551615, but given 76832(after align)
[ERROR] ASCENDCL(1160425,python):2023-07-14-16:01:13.752.718 [op_executor.cpp:192]1160425 DoExecuteAsync: [FINAL][FINAL][Exec][Op]Execute op failed. ge result = 145000

**Comment by 535205856** [comment]
再问下paddledetection中的那个网络，经过你们验证没问题的？
