### ISSUE TITLE
[BUG] nearest interpolate 单测 bug

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleCustomDevice#717]
1. TestNearestInterpOp_attr_tensor
<img width="754" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/31957460/b7e9db3a-52c3-4ed9-810e-58aff1ac067c">

432-433行会覆盖`self.init_test_case()`中变量

2. TestNearestInterpOp
<img width="646" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/31957460/04a8bf61-1308-4f9a-8854-f764e601b8b7">

167行会覆盖`self.init_test_case()`中变量

关联PR：https://github.com/PaddlePaddle/PaddleCustomDevice/pull/716

**Comment by YanhuiDua** [comment]
感谢贡献~
