### ISSUE TITLE
[NPU][Pass] 同样的网络结构，如果加入了while算子，那么Patter函数就匹配不上了

### ISSUE THREAD

**Issue by linboyang** [PaddlePaddle/PaddleCustomDevice#724]
## 问题：
1. 同样的网络结构，加上while算子之后，pattern没匹配上
2. while 算子内部的结构也未匹配上。
## 复现的代码如下：
```python
import paddle
import numpy as np
from paddle.incubate.passes import ir

@paddle.incubate.passes.ir.RegisterPass
def generate_add_n():
    def pattern(x, y, cache):
        cached_y = ir.PassDesc.OP.concat(X=[cache, y])
        matmul_result = ir.PassDesc.OP.matmul_v2(X=x, Y=cached_y)   
        return matmul_result, cached_y  # 代码更新

    def replace(x, y, cache):
        return paddle.incubate.passes.ir.PassDesc.OP.my_add_n(X=x, Y=y, Z=cache)
    return pattern, replace

@paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y'), paddle.static.InputSpec([1, 1], 'int32', 'loop_cnt')])
def func(x, y, loop_cnt):
    
    cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
    y = paddle.tensor.concat([cache_, y], axis=-1)
    result = paddle.matmul(x, y)

    i = paddle.to_tensor([0], dtype="int32")
    while i < paddle.squeeze(loop_cnt, 1):
        if cache_ is not None:
            y = paddle.tensor.concat([cache_, y], axis=-1)
        result = paddle.matmul(x, y)
        # cache_ = paddle.assign(y)
        cache_ = y
        paddle.increment(i)
    return result

# 如果使用如下函数，那么pass可以匹配。
@paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y')])
def func_without_while(x, y):
    cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
    y = paddle.tensor.concat([cache_, y], axis=-1)
    result = paddle.matmul(x, y)
    return result

paddle.utils.cpp_extension.extension_utils.load_op_meta_info_and_register_op('/opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so')
print(func.concrete_program.main_program)
model_file = './saved_models/func'
paddle.jit.save(func, model_file)

# inference
config = paddle.inference.Config()
config.set_prog_file(model_file + '.pdmodel')
config.enable_custom_device('npu')
config.enable_memory_optim()
pass_builder = config.pass_builder()
pass_builder.append_pass('generate_add_n')
paddle.fluid.core.register_subgraph_pass("generate_add_n")
pass_builder.turn_on_debug()

print(pass_builder.all_passes())
predictor = paddle.inference.create_predictor(config)
np_inputs = [
            np.ones((2, 2)).astype("float32"),
            np.ones((2, 2)).astype("float32"),
            np.ones((1, 1)).astype("int32"),
        ]
input_names = predictor.get_input_names()
for i, name in enumerate(input_names):
    input_tensor = predictor.get_input_handle(name)
    input_tensor.copy_from_cpu(np_inputs[i])
# input_names = predictor.get_input_names()
# for i, name in enumerate(input_names):
#     input_tensor = predictor.get_input_handle(name)
#     input_tensor.copy_from_cpu(np.random.randn(2, 2).astype('float32'))

predictor.run()
results = []
output_names = predictor.get_output_names()
for i, name in enumerate(output_names):
    output_tensor = predictor.get_output_handle(name)
    output_data = output_tensor.copy_to_cpu()
    results.append(output_data)
print(results)
```

**Comment by linboyang** [comment]
下图是加了while算子的split算子图。
从图上看到，split算子出来了4条线，其中最左边的横线连接到while算子，左2线是v线（q,k,v中的v），左3线是和左1线是同一条线（q,k,v中的k）。
猜测原因可能是加了while算子之后，split算子出来的线多了。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/22309864/c8594b80-ae52-410f-b069-973fef38c3e5)

**Comment by linboyang** [comment]
下图我想匹配红圈里面的算子，第一个elementwise add 算子出来了两条线，左边的线和右边的线输出的内容是一样的。这个时候Pattern也未匹配到。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/22309864/cf39af2b-5ec5-442d-be48-b9a3a7fd3c31)

**Comment by ronny1996** [comment]
> ## 问题：
> 1. 同样的网络结构，加上while算子之后，pattern没匹配上
> 2. while 算子内部的结构也未匹配上。
> 
> ## 复现的代码如下：
> ```python
> import paddle
> import numpy as np
> from paddle.incubate.passes import ir
> 
> @paddle.incubate.passes.ir.RegisterPass
> def generate_add_n():
>     def pattern(x, y, cache):
>         cached_y = ir.PassDesc.OP.concat(X=[cache, y])
>         return ir.PassDesc.OP.matmul_v2(X=x, Y=cached_y)
> 
>     def replace(x, y, cache):
>         return paddle.incubate.passes.ir.PassDesc.OP.my_add_n(X=x, Y=y, Z=cache)
>     return pattern, replace
> 
> @paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y'), paddle.static.InputSpec([1, 1], 'int32', 'loop_cnt')])
> def func(x, y, loop_cnt):
>     
>     cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
>     y = paddle.tensor.concat([cache_, y], axis=-1)
>     result = paddle.matmul(x, y)
> 
>     i = paddle.to_tensor([0], dtype="int32")
>     while i < paddle.squeeze(loop_cnt, 1):
>         if cache_ is not None:
>             y = paddle.tensor.concat([cache_, y], axis=-1)
>         result = paddle.matmul(x, y)
>         # cache_ = paddle.assign(y)
>         cache_ = y
>         paddle.increment(i)
>     return result
> 
> # 如果使用如下函数，那么pass可以匹配。
> @paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y')])
> def func_without_while(x, y):
>     cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
>     y = paddle.tensor.concat([cache_, y], axis=-1)
>     result = paddle.matmul(x, y)
>     return result
> 
> paddle.utils.cpp_extension.extension_utils.load_op_meta_info_and_register_op('/opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so')
> print(func.concrete_program.main_program)
> model_file = './saved_models/func'
> paddle.jit.save(func, model_file)
> 
> # inference
> config = paddle.inference.Config()
> config.set_prog_file(model_file + '.pdmodel')
> config.enable_custom_device('npu')
> config.enable_memory_optim()
> pass_builder = config.pass_builder()
> pass_builder.append_pass('generate_add_n')
> paddle.fluid.core.register_subgraph_pass("generate_add_n")
> pass_builder.turn_on_debug()
> 
> print(pass_builder.all_passes())
> predictor = paddle.inference.create_predictor(config)
> np_inputs = [
>             np.ones((2, 2)).astype("float32"),
>             np.ones((2, 2)).astype("float32"),
>             np.ones((1, 1)).astype("int32"),
>         ]
> input_names = predictor.get_input_names()
> for i, name in enumerate(input_names):
>     input_tensor = predictor.get_input_handle(name)
>     input_tensor.copy_from_cpu(np_inputs[i])
> # input_names = predictor.get_input_names()
> # for i, name in enumerate(input_names):
> #     input_tensor = predictor.get_input_handle(name)
> #     input_tensor.copy_from_cpu(np.random.randn(2, 2).astype('float32'))
> 
> predictor.run()
> results = []
> output_names = predictor.get_output_names()
> for i, name in enumerate(output_names):
>     output_tensor = predictor.get_output_handle(name)
>     output_data = output_tensor.copy_to_cpu()
>     results.append(output_data)
> print(results)
> ```

你好，例子里加while匹配不上是符合预期的，while内使用了while外的算子输出，即都作为了while的输入，pattern缺少了这些输出

**Comment by linboyang** [comment]
> > ## 问题：
> > 
> > 1. 同样的网络结构，加上while算子之后，pattern没匹配上
> > 2. while 算子内部的结构也未匹配上。
> > 
> > ## 复现的代码如下：
> > ```python
> > import paddle
> > import numpy as np
> > from paddle.incubate.passes import ir
> > 
> > @paddle.incubate.passes.ir.RegisterPass
> > def generate_add_n():
> >     def pattern(x, y, cache):
> >         cached_y = ir.PassDesc.OP.concat(X=[cache, y])
> >         return ir.PassDesc.OP.matmul_v2(X=x, Y=cached_y)
> > 
> >     def replace(x, y, cache):
> >         return paddle.incubate.passes.ir.PassDesc.OP.my_add_n(X=x, Y=y, Z=cache)
> >     return pattern, replace
> > 
> > @paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y'), paddle.static.InputSpec([1, 1], 'int32', 'loop_cnt')])
> > def func(x, y, loop_cnt):
> >     
> >     cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
> >     y = paddle.tensor.concat([cache_, y], axis=-1)
> >     result = paddle.matmul(x, y)
> > 
> >     i = paddle.to_tensor([0], dtype="int32")
> >     while i < paddle.squeeze(loop_cnt, 1):
> >         if cache_ is not None:
> >             y = paddle.tensor.concat([cache_, y], axis=-1)
> >         result = paddle.matmul(x, y)
> >         # cache_ = paddle.assign(y)
> >         cache_ = y
> >         paddle.increment(i)
> >     return result
> > 
> > # 如果使用如下函数，那么pass可以匹配。
> > @paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y')])
> > def func_without_while(x, y):
> >     cache_ = paddle.to_tensor([[1.0, 2.0],[1.0, 2.0]], dtype="float32")
> >     y = paddle.tensor.concat([cache_, y], axis=-1)
> >     result = paddle.matmul(x, y)
> >     return result
> > 
> > paddle.utils.cpp_extension.extension_utils.load_op_meta_info_and_register_op('/opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so')
> > print(func.concrete_program.main_program)
> > model_file = './saved_models/func'
> > paddle.jit.save(func, model_file)
> > 
> > # inference
> > config = paddle.inference.Config()
> > config.set_prog_file(model_file + '.pdmodel')
> > config.enable_custom_device('npu')
> > config.enable_memory_optim()
> > pass_builder = config.pass_builder()
> > pass_builder.append_pass('generate_add_n')
> > paddle.fluid.core.register_subgraph_pass("generate_add_n")
> > pass_builder.turn_on_debug()
> > 
> > print(pass_builder.all_passes())
> > predictor = paddle.inference.create_predictor(config)
> > np_inputs = [
> >             np.ones((2, 2)).astype("float32"),
> >             np.ones((2, 2)).astype("float32"),
> >             np.ones((1, 1)).astype("int32"),
> >         ]
> > input_names = predictor.get_input_names()
> > for i, name in enumerate(input_names):
> >     input_tensor = predictor.get_input_handle(name)
> >     input_tensor.copy_from_cpu(np_inputs[i])
> > # input_names = predictor.get_input_names()
> > # for i, name in enumerate(input_names):
> > #     input_tensor = predictor.get_input_handle(name)
> > #     input_tensor.copy_from_cpu(np.random.randn(2, 2).astype('float32'))
> > 
> > predictor.run()
> > results = []
> > output_names = predictor.get_output_names()
> > for i, name in enumerate(output_names):
> >     output_tensor = predictor.get_output_handle(name)
> >     output_data = output_tensor.copy_to_cpu()
> >     results.append(output_data)
> > print(results)
> > ```
> 
> 你好，例子里加while匹配不上是符合预期的，while内使用了while外的算子输出，即都作为了while的输入，pattern缺少了这些输出
那你能否给出一份可以匹配的Pattern？我把pattern的return 值改成了 return matmul_result, cached_y。好像还是不行。修改后的Patter如下：
```python
@paddle.incubate.passes.ir.RegisterPass
def generate_add_n():
    def pattern(x, y, cache):
        cached_y = ir.PassDesc.OP.concat(X=[cache, y])
        matmul_result = ir.PassDesc.OP.matmul_v2(X=x, Y=cached_y)
        return matmul_result, cached_y

    def replace(x, y, cache):
        return paddle.incubate.passes.ir.PassDesc.OP.my_add_n(X=x, Y=y, Z=cache)
    return pattern, replace
```

**Comment by linboyang** [comment]
关于同一个输出连接到两个不同的算子的匹配demo：
下面的代码是我想匹配下图里红圈的算子，但是却未匹配上。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/22309864/49f99901-ca9c-4260-bbaa-cda2d79f5955)


```python
import paddle 
import paddle.nn as nn
import numpy as np

from paddle.incubate.passes import ir
import paddle_custom_device.npu.passes as passes


@paddle.incubate.passes.ir.RegisterPass
def gen_fuse_res_add():
    def pattern(x, y):
        #resadd
        add_out = ir.PassDesc.OP.elementwise_add(X=x, Y=y)
        gelu_out = ir.PassDesc.OP.gelu(X=add_out)
        #！！！！ 这里如果去掉下面两行注释是可以匹配到整图的。
        # res_add_out_2 = ir.PassDesc.OP.elementwise_add(X=add_out, Y=gelu_out)
        # return res_add_out_2
        return add_out, gelu_out

    def replace(x, y):
        return ir.PassDesc.OP.my_add_n(X=x, Y=y, Z=y)
    
    return pattern, replace


@paddle.jit.to_static(input_spec=[paddle.static.InputSpec([2, 2], 'float32', 'x'),  paddle.static.InputSpec([2, 2], 'float32', 'y')])
def func(x, y):
    z = x + y
    tmp = nn.GELU()(z)
    result = z + tmp
    return result


paddle.utils.cpp_extension.extension_utils.load_op_meta_info_and_register_op('/opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so')
print(func.concrete_program.main_program)
model_file = './saved_models/func'
paddle.jit.save(func, model_file)

# inference
config = paddle.inference.Config()
config.set_prog_file(model_file + '.pdmodel')
config.enable_custom_device('npu')
config.enable_memory_optim()
pass_builder = config.pass_builder()
pass_builder.append_pass('gen_fuse_res_add')
paddle.fluid.core.register_subgraph_pass("gen_fuse_res_add")
pass_builder.turn_on_debug()

print(pass_builder.all_passes())
predictor = paddle.inference.create_predictor(config)
np_inputs = [
            np.ones((2, 2)).astype("float32"),
            np.ones((2, 2)).astype("float32"),
        ]
input_names = predictor.get_input_names()
for i, name in enumerate(input_names):
    input_tensor = predictor.get_input_handle(name)
    input_tensor.copy_from_cpu(np_inputs[i])
# input_names = predictor.get_input_names()
# for i, name in enumerate(input_names):
#     input_tensor = predictor.get_input_handle(name)
#     input_tensor.copy_from_cpu(np.random.randn(2, 2).astype('float32'))

predictor.run()
results = []
output_names = predictor.get_output_names()
for i, name in enumerate(output_names):
    output_tensor = predictor.get_output_handle(name)
    output_data = output_tensor.copy_to_cpu()
    results.append(output_data)
print(results)
```

**Comment by ronny1996** [comment]
https://github.com/PaddlePaddle/Paddle/pull/55728

你好，这个PR应该修复了这个问题
