### ISSUE TITLE
[MLU][BUG] fix rsqrt ut

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleCustomDevice#734]
<img width="547" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/31957460/de9fac1b-94db-4f5d-92a4-7165b893c2e6">

关联PR：https://github.com/PaddlePaddle/PaddleCustomDevice/pull/726

**Comment by qili93** [comment]
Close as PR merged, thanks for your contribution.
