### ISSUE TITLE
[MLU][NPU][BUG] fix nearest_interp_v2 case & add 2D sacle tensor case

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleCustomDevice#735]
1. `set_align_corners `没有调用，导致`TestNearestInterpWithoutCorners`测例未覆盖
<img width="599" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/31957460/fc001fd9-bab7-4473-9429-d71825cdd696">

2. 增加`scale_by_2Dtensor `的case，覆盖kernel中scale tensor size > 1的情况
<img width="1096" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/31957460/ce7d9b71-5f41-482b-bc7c-64de79a15e2b">

**Comment by YanhuiDua** [comment]
你好，感谢贡献代码~
