### ISSUE TITLE
[MLU] bloom-560M训练爆显存

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/PaddleCustomDevice#736]
相关版本：

- python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html
- PaddleCustomDevice-develop分支

执行步骤：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/bloom#%E6%A8%A1%E5%9E%8B-finetune

**Comment by YanhuiDua** [comment]
你好，请问你使用的设备显存是多大呢？

**Comment by YanhuiDua** [comment]
你好，我这里用npu测试了bloom-560m训练，显存占用正常，可以打开GLOG_v=8，看下Paddle/paddle/fluid/memory/stats.h中的log: "Update current_value with *,   after update, current value = *"，寻找下MLU中哪一个kernel显存增加很多

**Comment by Ivorfeng** [comment]
你好，请问下“用npu测试了bloom-560m训练，显存占用正常”这个每张卡占用多少GB显存呢？
我这边发现是反向的时候，显存从2GB ->18GB->24GB,导致超过板卡的显存挂了；
TP=4时，vocab_size 不做拆分吗？c_softmax_with_cross_entropy的时候 存在（4，479，250880）这个比较大的规模， 对560m这样的模型来说，内存占用似乎不太合理？
