### ISSUE TITLE
自定义Pass中，无法提取被融合算子的权重

### ISSUE THREAD

**Issue by ChengleiTian** [PaddlePaddle/PaddleCustomDevice#750]
你好，在我下面的例子里面, 会将MyTest的forward替换为my_ln, LayerNorm中的属性值epsilon，可以通过MappedPattern获取到，
但是无法获取到LayerNorm算子的Bias和Scale, 请问有什么办法可以得到被融合算子的可学习参数张量？

```
@paddle.incubate.passes.ir.RegisterPass
def generate_my_ln():
    def pattern(x):
        ln_op = IR.PassDesc.OP.layer_norm
        ln_op._outputs.pop("Mean")
        ln_op._outputs.pop("Variance")
        ln_out = ln_op(X=x)

        return ln_out

    def replace(x):
        fuse_op = IR.PassDesc.OP.my_ln(X=x, Y=x)
        fuse_op.Attr("epsilon").MappedPattern(
            op="layer_norm", name="epsilon"
        )
        fuse_op.SetAttr("transpose_x", True)
        fuse_op.SetAttr("transpose_y", False)

        return fuse_op

    return pattern, replace


class MyTest(paddle.nn.Layer):
    def __init__(
        self
    ):
        super().__init__()
        self.ln_op = paddle.nn.LayerNorm(2, epsilon=0.000345, weight_attr=True, bias_attr=True)

    def forward(self, x):
        ln_out = self.ln_op(x)
        return ln_out
```

**Comment by ronny1996** [comment]
scale 和 bias 应该为算子的输入，与 x 一样作为 pattern 的输入

**Comment by ChengleiTian** [comment]
有没有例子可供参考？

**Comment by ChengleiTian** [comment]
请问，下面的例子，匹配的时候，怎么样才可以把MyTest模型中Linear算子的weight和bias传入自定义MyLinear?
这个pass可以跑，但是我的C++函数中weight是个空的DenseTensor


> scale 和 bias 应该为算子的输入，与 x 一样作为 pattern 的输入

@paddle.incubate.passes.ir.RegisterPass
def generate_my_linear():
    def pattern(x, weight, bias):
        return paddle.add(paddle.matmul(x, weight), bias)

    def replace(x, weight, bias):
        fuse_op = IR.PassDesc.OP.MyLinear(X=x, Weight=weight, Bias=bias)
        fuse_op.SetAttr("epsilon", 0.000125)
        fuse_op.SetAttr("transpose_x", True)
        fuse_op.SetAttr("transpose_y", False)

        return fuse_op

    return pattern, replace


class MyTest(paddle.nn.Layer):
    def __init__(
        self
    ):
        super().__init__()
        weight_attr = paddle.ParamAttr(
            name="weight",
            initializer=paddle.nn.initializer.Constant(value=0.5))
        bias_attr = paddle.ParamAttr(
            name="bias",
            initializer=paddle.nn.initializer.Constant(value=1.0))

        self.linear = linear = paddle.nn.Linear(2, 2, weight_attr=weight_attr, bias_attr=bias_attr);

    def forward(self, x):
        linear_out = self.linear(x)
        return linear_out

**Comment by qili93** [comment]
参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/custom_op/fused_mm_reduce_scatter.cc#L25 ，这里的bias也是作为算子的输入。

**Comment by qili93** [comment]
您好，这个问题是否已经解决，谢谢！

**Comment by ChengleiTian** [comment]
Fixed

**Comment by qili93** [comment]
收到，那我就关闭这个ISSUE了，多谢！
