### ISSUE TITLE
[Paddle]请问当前反向算子的实现是否有像pytorch那样的autograd计算机制?

### ISSUE THREAD

**Issue by DeshuaiSun** [PaddlePaddle/PaddleCustomDevice#759]
- 例如：div_grad
- 在pytorch中div_grad调用div_tensor_self_backward实现，div_tensor_self_backward调用其他算子实现，具体怎么实现是框架自己的逻辑，paddle中是否有相应的机制？

**Comment by qili93** [comment]
您好，这个问题请到 Paddle主框架 https://github.com/PaddlePaddle/Paddle 进行提问，PaddleCustomDevice仅涉及硬件适配相关的问题，谢谢！

**Comment by qili93** [comment]
Close as no more comments in last 7 days.
