### ISSUE TITLE
NPU上每个device显示有重复的进程id

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/PaddleCustomDevice#767]
NPU上每个device显示有重复的进程id，只占用少量显存，类似僵尸进程

**Comment by zhjc** [comment]
如下，进程 47881 在device 0 为业务进程，在device 1是僵尸进程
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)	 |
+===========================+===============+====================================================+
| 0       0                 | 47928         | python                   | 90                      |
| 0       0                 | 47896         | python                   | 90                      |
| 0       0                 | 47920         | python                   | 90                      |
| 0       0                 | 47907         | python                   | 90                      |
| 0       0                 | 47910         | python                   | 90                      |
| 0       0                 | 47913         | python                   | 90                      |
| 0       0                 | 47881         | python                   | 4184                    |
| 0       0                 | 47892         | python                   | 90                      |
+===========================+===============+====================================================+
| 1       0                 | 47928         | python                   | 90                      |
| 1       0                 | 47896         | python                   | 90                      |
| 1       0                 | 47920         | python                   | 89                      |
| 1       0                 | 47907         | python                   | 89                      |
| 1       0                 | 47910         | python                   | 90                      |
| 1       0                 | 47913         | python                   | 90                      |
| 1       0                 | 47881         | python                   | 103                     |
| 1	  0                 | 47892         | python                   | 4169                    |
+===========================+===============+====================================================+
| 2	  0                 | 47928         | python                   | 89                      |

**Comment by ronny1996** [comment]
Fixed https://github.com/PaddlePaddle/Paddle/pull/56580
