### ISSUE TITLE
Paddle PR-CI-Py3流水线对custom-cpu的测试用例有随机挂现象

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/PaddleCustomDevice#770]
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/9016046/job/23646338
以此（实际上在此流水线相邻的测试中也出现了类似的现象）为例，31544行出现空指针，能否帮忙排查一下该问题。

**Comment by ronny1996** [comment]
你好，已经在修了

**Comment by jinyouzhi** [comment]
> 你好，已经在修了

👍
