### ISSUE TITLE
[NPU]PaddleCustomDevice编译安装后import paddle失败

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/PaddleCustomDevice#783]
Paddle版本：7c8c9b7d87b51838ae6ed379ac9bc3d5685b7bee
PaddleCustomDevice版本：0a9d29c7839277447b78138c62ec928f17926ef8

Paddle编译命令：
```
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_CUSTOM_DEVICE=ON -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=ON -DWITH_XBYAK=OFF -DWITH_ARM=ON

make TARGET=ARMV8 -j64
```

PaddleCustomDevice命令：
```
cd backends/npu
bash tools/compile.sh
```

生成的两个whl包使用pip安装后，执行`import paddle`，报错如下：
```
>>> import paddle
I0907 16:59:06.533313 39583 init.cc:237] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0907 16:59:06.533385 39583 init.cc:146] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
paddle flags error: illegal RegisterFlag, flag "devices" has been defined in /home/xxx/paddle/fluid/inference/io.cc (at /home/xxx/paddle/utils/flags_native.cc:301)

```

**Comment by zhjc** [comment]
拉取最新Paddle代码：d8122a23d5068d21f74c11eb4bb8e0a5b779d567
编译错误:
```
xxx/fluid/ir/dialect/paddle_dialect/ir/pd_manual_op.cc:163:16: error: no matching function for call to ‘paddle::dialect::OpInputInfo::OpInputInfo(const char [7], const char [49], bool, bool, bool)’
           false)};
```

**Comment by ronny1996** [comment]
7c8c9b我没有复现你的问题，请问你的编译命令是什么？

![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/25691046/998e1b23-4af8-413c-90ce-fc8b65b4973f)

**Comment by ronny1996** [comment]
> 拉取最新Paddle代码：d8122a23d5068d21f74c11eb4bb8e0a5b779d567 编译错误:
> 
> ```
> xxx/fluid/ir/dialect/paddle_dialect/ir/pd_manual_op.cc:163:16: error: no matching function for call to ‘paddle::dialect::OpInputInfo::OpInputInfo(const char [7], const char [49], bool, bool, bool)’
>            false)};
> ```

https://github.com/PaddlePaddle/Paddle/pull/57033 这个pr修复了这个问题
