### ISSUE TITLE
[MLU] 自动混合精度规约算子特化处理问题

### ISSUE THREAD

**Issue by DeshuaiSun** [PaddlePaddle/PaddleCustomDevice#810]
当前MLU实现中规约算子是否已支持自动混合精度的特化处理？根据[自动混合精度训练（AMP）](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/performance_improving/amp_cn.html)中的介绍，当前paddle框架已支持MLU的混合精度训练，但根据[低精度算子支持开发规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/amp_precision/amp_op_dev_guide_cn.html)中的介绍当前规约算子及部分数学函数计算并无特化处理，请问当前MLU支持自动混合精度采用了哪种方案？

**Comment by qili93** [comment]
您好，当前MLU支持AMP混合精度训练，FP16 的 O1 和 O2都支持，暂不支持BF16。

**Comment by qili93** [comment]
您好，请问关于MLU的AMP是否还有更多问题呢？

如果没有请帮忙关闭此ISSUE，谢谢！
