### ISSUE TITLE
FusedAllReduce使用Concat和Split算子？

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/PaddleCustomDevice#811]
当前实现中，concat和split使用memcpy实现，是否考虑使用concat和split算子实现？

**Comment by qili93** [comment]
请问您这里具体指的是哪个硬件的实现呢？

**Comment by qili93** [comment]
2周未有新的comments，关闭此issue。如果您有新的问题，可以open新的issue提问，谢谢！
