### ISSUE TITLE
[MLU] 安装不成功

### ISSUE THREAD

**Issue by baominghelly** [PaddlePaddle/PaddleCustomDevice#820]
MLU安装后，import paddle不成功，哪位大佬可以提供安装的docker镜像和安装包呢？

**Comment by qili93** [comment]
您好，飞桨暂不对外提供预编译的安装包，请参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/mlu/README_cn.md 这个文档进行镜像拉取和源码编译。

**Comment by qili93** [comment]
Close as no more comments in last 7 days.
