### ISSUE TITLE
昇腾910B和CANN7.0.RC1出现错误

### ISSUE THREAD

**Issue by Wall-cn** [PaddlePaddle/PaddleCustomDevice#834]
参考文档：https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
环境信息：官网EulerOs系统的Dockerfile修改成CANN7.0.RC1，python=3.9，gcc82
出错命令：python tests/test_LeNet_MNIST.py
完整的错误信息：python tests/test_LeNet_MNIST.py
I1108 08:56:44.854535 114008 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device
I1108 08:56:44.854583 114008 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device]
I1108 08:56:45.166314 114008 custom_device.cc:1108] Successed in loading custom runtime in lib: /root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I1108 08:56:45.168068 114008 custom_kernel.cc:63] Successed in loading 326 custom kernel(s) from loaded lib(s), will be used like native ones.
I1108 08:56:45.168195 114008 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device]
I1108 08:56:45.168227 114008 init.cc:239] CustomDevice: npu, visible devices count: 8
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
Traceback (most recent call last):
  File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 261, in <module>
    main(args)
  File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 162, in main
    outputs = model(images)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/vision/models/lenet.py", line 67, in forward
    x = self.features(inputs)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/container.py", line 614, in forward
    input = layer(input)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 715, in forward
    out = F.conv._conv_nd(
  File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/functional/conv.py", line 128, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External)  ACL error, the error code is : 500001.  (at /work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.cc:422)
请问能解决吗？目前在国产化项目中之前都是基于910A的，该怎么做呢？目前项目比较急。

**Comment by Wall-cn** [comment]
> 参考文档：https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 环境信息：官网EulerOs系统的Dockerfile修改成CANN7.0.RC1，python=3.9，gcc82 出错命令：python tests/test_LeNet_MNIST.py 完整的错误信息：python tests/test_LeNet_MNIST.py I1108 08:56:44.854535 114008 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device I1108 08:56:44.854583 114008 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device] I1108 08:56:45.166314 114008 custom_device.cc:1108] Successed in loading custom runtime in lib: /root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so I1108 08:56:45.168068 114008 custom_kernel.cc:63] Successed in loading 326 custom kernel(s) from loaded lib(s), will be used like native ones. I1108 08:56:45.168195 114008 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device] I1108 08:56:45.168227 114008 init.cc:239] CustomDevice: npu, visible devices count: 8 ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough Traceback (most recent call last): File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 261, in main(args) File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 162, in main outputs = model(images) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/vision/models/lenet.py", line 67, in forward x = self.features(inputs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/container.py", line 614, in forward input = layer(input) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 715, in forward out = F.conv._conv_nd( File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/functional/conv.py", line 128, in _conv_nd pre_bias = _C_ops.conv2d( OSError: (External) ACL error, the error code is : 500001. (at /work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.cc:422) 请问能解决吗？目前在国产化项目中之前都是基于910A的，该怎么做呢？目前项目比较急。

我把shm的大小调到了128G又出现了下面的问题：
python tests/test_LeNet_MNIST.py
I1108 10:33:34.978806  3040 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device
I1108 10:33:34.978842  3040 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device]
I1108 10:33:35.127214  3040 custom_device.cc:1108] Successed in loading custom runtime in lib: /root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I1108 10:33:35.128859  3040 custom_kernel.cc:63] Successed in loading 326 custom kernel(s) from loaded lib(s), will be used like native ones.
I1108 10:33:35.128979  3040 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device]
I1108 10:33:35.129009  3040 init.cc:239] CustomDevice: npu, visible devices count: 8
Call aclrtSynchronizeStream(reinterpret_cast<aclrtStream>(stream)) failed : 507001 at file /workspace/PaddleCustomDevice/backends/npu/runtime/runtime.cc line 685
EE9999: Inner Error, Please contact support engineer!
EE9999  Memory async copy failed, device_id=0, stream_id=1, task_id=0, flip_num=0, copy_type=0, memcpy_type=1, copy_data_type=0, length=1[FUNC:GetError][FILE:stream.cc][LINE:1044]
        TraceBack (most recent call last):
        rtStreamSynchronize execute failed, reason=[tsfw unknown error][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:49]
        synchronize stream failed, runtime result = 507001[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_gaussian(_object*, _object*, _object*)
1   gaussian_ad_func(paddle::experimental::IntArrayBase<paddle::Tensor>, float, float, int, phi::DataType, phi::Place)
2   paddle::experimental::gaussian(paddle::experimental::IntArrayBase<paddle::Tensor> const&, float, float, int, phi::DataType, phi::Place const&)
3   void custom_kernel::GaussianKernel<float, phi::CustomContext>(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, float, float, int, phi::DataType, phi::DenseTensor*)
4   void custom_kernel::TensorCopy<phi::CustomContext>(phi::CustomContext const&, phi::DenseTensor const&, bool, phi::DenseTensor*, phi::Place const&)
5   phi::CustomDevice::SynchronizeStream(unsigned long, phi::stream::Stream const*)
6   SyncStream(C_Device_st*, C_Stream_st*)
7   phi::DeviceManager::~DeviceManager()
8   std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::unique_ptr<phi::Device, std::default_delete<phi::Device> >, std::allocator<std::unique_ptr<phi::Device, std::default_delete<phi::Device> > > > >, std::allocator<std::pair<std::string const, std::vector<std::unique_ptr<phi::Device, std::default_delete<phi::Device> >, std::allocator<std::unique_ptr<phi::Device, std::default_delete<phi::Device> > > > > >, std::__detail::_Select1st, std::equal_to<std::string >, std::hash<std::string >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear()
9   phi::CustomDevice::DeInitDevice(unsigned long)
10  ReleaseDevice(C_Device_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1699439615 (unix time) try "date -d @1699439615" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x10000000f) received by PID 3040 (TID 0xffff9ece4900) from PID 15 ***]

Segmentation fault (core dumped)

**Comment by YanhuiDua** [comment]
你好，可以看下目录/usr/local/Ascend目录下asend的报错log，看下有什么报错信息

**Comment by Wall-cn** [comment]
> 你好，可以看下目录/usr/local/Ascend目录下asend的报错log，看下有什么报错信息

你好，我这边在昇腾910B物理机上使用hccn_tool给每张卡分配ip之后，刚才我运行这个测试样例的时候，它就通过了，我也不清楚什么原因......

**Comment by Wall-cn** [comment]
> 1108 08:56:44.854535 114008 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device I1108 08:56:44.854583 114008 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device] I1108 08:56:45.166314 114008 custom_device.cc:1108] Successed in loading custom runtime in lib: /root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so I1108 08:56:45.168068 114008 custom_kernel.cc:63] Successed in loading 326 custom kernel(s) from loaded lib(s), will be used like native ones. I1108 08:56:45.168195 114008 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle_custom_device] I1108 08:56:45.168227 114008 init.cc:239] CustomDevice: npu, visible devices count: 8 ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough Traceback (most recent call last): File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 261, in main(args) File "/work/PaddleCustomDevice/backends/npu/tests/test_LeNet_MNIST.py", line 162, in main outputs = model(images) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/vision/models/lenet.py", line 67, in forward x = self.features(inputs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/container.py", line 614, in forward input = layer(input) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1343, in **call** return self.forward(*inputs, **kwargs) File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 715, in forward out = F.conv._conv_nd( File "/root/miniconda3/envs/paddle-npu/lib/python3.9/site-packages/paddle/nn/functional/conv.py", line 128, in _conv_nd pre_bias = _C_ops.conv2d( OSError: (External) ACL error, the error code is : 500001. (at /work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.cc:422) 请问能解决吗？目前在国产化项目中之前都是基于910A的，该怎么做呢？目前项目比较急。

**Comment by Wall-cn** [comment]
> > 你好，可以看下目录/usr/local/Ascend目录下asend的报错log，看下有什么报错信息
> 
> 你好，我这边在昇腾910B物理机上使用hccn_tool给每张卡分配ip之后，刚才我运行这个测试样例的时候，它就通过了，我也不清楚什么原因......

![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/50002649/e409c54e-9cf6-4866-8d44-6e1b732004a3)
