### ISSUE TITLE
昇腾910B训练PaddleDetection框架中的检测报错

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/PaddleCustomDevice#840]
![717db6e972750f30eb3a8960e27a43a9](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/45171399/e97cc87d-cd60-4b43-afc1-4ff9dd4291b9)

vitbase+dino检测head，paddledet版本是2.6，如何解决

**Comment by qili93** [comment]
您好，这个模型我们之前在昇腾910B上暂未验证过，存在无法支持的情况。我们会记录这个需求，放到后续支持的需求池中进行评审，谢谢！
