### ISSUE TITLE
Paddle官方有提供cann7.0版本的镜像环境吗？

### ISSUE THREAD

**Issue by ben1017-maker** [PaddlePaddle/PaddleCustomDevice#846]
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md，官方链接只有cann6.0.1

**Comment by BrightXiaoHan** [comment]
最新版本文档地址支持cann7.0，https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu。

但是镜像下载好像有点问题。#878

**Comment by BrightXiaoHan** [comment]
请问文档中的镜像什么时候可以下载呢？

**Comment by qili93** [comment]
您好，镜像已经重新上传，请再试下 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 文档中的镜像
