### ISSUE TITLE
求助算子属性不会跟随输入改变

### ISSUE THREAD

**Issue by bmers** [PaddlePaddle/PaddleCustomDevice#856]
rebuild_padding_v2算子中，有一个max_input_length属性，图中值为1430
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/de7d2daa-c145-4ffb-9b61-b8437e9ef196)
该1430具体是，从参数kwargs["max_input_length"]读取到的，具体与export静态图时设置的输入长度src_length有关。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/182dfc77-396f-42bb-9122-478ef0dde53a)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/f238fb8b-21cb-40ba-9128-7ed8eb7f97eb)

实际使用这个静态图运行时，如果给src_length与导出export时设置的不一样，这个max_input_length属性并不会跟随输入改变，还是1430。
如果我将组网代码修改一下，尝试从input_ids的shape中获取max_input_length信息时，导出模型又会报错。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/f3eef19b-48d2-485f-b120-e4edf29b0dfc)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/b57f2702-538a-47b0-8fbd-99bf7e208480)

**Comment by bmers** [comment]
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/3fd76b2d-641b-46fd-9a93-1b26f33d8d4c)
放大：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/e9814d93-5eb6-48fe-8559-184c0be8ca8e)
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/c18a983f-21b0-474a-8f29-0257e6e069a6)

**Comment by bmers** [comment]
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/599d4e64-cf88-402c-9329-d18964594130)

**Comment by bmers** [comment]
落tensor
```cpp
#include <fstream>
template<typename T>
void WriteTensorToFile(const std::string name, T* data, size_t num)
{
    std::ofstream of(name + ".bin", std::ios::out | std::ios::binary);
    of.write(reinterpret_cast<char *>(data), num * sizeof(T));
    of.close();
}
WriteTensorToFile("distResult", distResult.data(), distResult.size());
```

**Comment by bmers** [comment]
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/29788896/74b7a700-9ace-4300-8dca-7ba8f8299130)

**Comment by qili93** [comment]
Close as LLaMA65B exported in https://github.com/MyAngelAyase/PaddleCustomDevice and https://github.com/MyAngelAyase/PaddleNLP
