### ISSUE TITLE
paddle-npu编译镜像device/paddle-npu:cann700-910B-ubuntu18-aarch64无法下载

### ISSUE THREAD

**Issue by 2022WPJ** [PaddlePaddle/PaddleCustomDevice#878]
文档地址：https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu
镜像地址：registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64
无法下载，报错信息：
Error response from daemon: manifest for registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64 not found: manifest unknown: manifest unknown

**Comment by BrightXiaoHan** [comment]
遇到同样的问题，请问有解决方案么？

**Comment by 2022WPJ** [comment]
> 遇到同样的问题，请问有解决方案么？

暂时用的上一个版本的
docker pull registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82

**Comment by BrightXiaoHan** [comment]
> > 遇到同样的问题，请问有解决方案么？
> 
> 暂时用的上一个版本的 docker pull registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82

registry.baidubce.com/device/paddle-npu:cann70RC1-910A-ubuntu18-aarch64 
我试了一下，这个镜像可以下载，在910B上也能正常使用

**Comment by qili93** [comment]
您好，镜像已经重新上传，请再试下 docker pull registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64

**Comment by 2022WPJ** [comment]
> 
您好，请问910A和910B有什么区别吗？

**Comment by qili93** [comment]
是2款不同的芯片，您可以在您的环境中使用以下命令查看芯片类型

昇腾910A芯片 - 系统环境下查看 lspci | grep d801 是否有输出

昇腾910B芯片 - 系统环境下查看 lspci | grep d802 是否有输出

这个在文档 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 也补充了相关说明

![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/16605440/65de9c1c-6175-4a76-b309-9b5a2b3c0783)

更多芯片差异请查询华为昇腾官网或联系华为昇腾的技术支持，谢谢！
