### ISSUE TITLE
registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64 镜像不存在

### ISSUE THREAD

**Issue by bigbosskai** [PaddlePaddle/PaddleCustomDevice#920]
docker pull registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64

镜像不存在！！！！！！
Error response from daemon: manifest for registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64 not found: manifest unknown: manifest unknown

**Comment by qili93** [comment]
您好，镜像已经重新上传，请再试下 `docker pull registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64`
