### ISSUE TITLE
PaddleCustomDevice仓自定义融合算子的Infershape函数问题

### ISSUE THREAD

**Issue by wanx7130** [PaddlePaddle/PaddleCustomDevice#922]
Hi，请教一下，当前想在推理场景下实现一些自定义的融合算子，但是在写Infershape时有点Confuse，不知道该如何定义Infershape函数，因为需要知道每个算子的属性、输入shape才能进行推导。在CustomDevice仓只看到了一个my_add_n的自定义算子推导，不是很详细，有没有更详细一点的示例供参考，谢谢！

**Comment by ronny1996** [comment]
你好，更多的infershape注册可以参考这个文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#weiduyuleixingtuidaohanshushixian

**Comment by wanx7130** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#weiduyuleixingtuidaohanshushixian

你好，再请教下，自定义算子的前向函数定义示例里看未将输出作为函数的输入传入，当自定义算子的输出shape和输入shape不一致时，是需要再从前向函数里额外显示调用下注册的Infershape函数吗？

**Comment by wanx7130** [comment]
std::vector<paddle::Tensor> AddForward(
    const paddle::Tensor& x,
    const paddle::optional<paddle::Tensor>& y) {  // NOLINT
  PD_CHECK(x.place() == paddle::PlaceType::kCPU, "x must be a CPU Tensor.");
  paddle::Tensor out = paddle::empty(x.shape(), x.dtype(), x.place());

  if (y) {
    out = x + y.get();
  } else {
    out = x + x;
  }

  return {out};
}

std::vector<paddle::DataType> AddInferDtype(
    const paddle::DataType& x_dtype,
    const paddle::optional<paddle::DataType>& y_dtype) {
  if (y_dtype) {
    return {*y_dtype};
  }
  return {x_dtype};
}

std::vector<std::vector<int64_t>> AddInferShape(
    const std::vector<int64_t>& x_shape,
    const paddle::optional<std::vector<int64_t>>& y_shape) {
  if (y_shape) {
    return {*y_shape};
  }
  return {x_shape};
}
比如示例这里的AddForward，其输入Tensor是在Forward里局部定义的，该如何获取输出shape？是否只能显示调用Infershape，这样是不是会存在一次计算两次调用Infershape的冗余？

**Comment by ronny1996** [comment]
你好，forward里目前只能显式调用infershape，会存在冗余
