### ISSUE TITLE
paddle custom device中接入multiclass_nms3时，custom_device在静态图执行器下无法正确识别输出tensor数据

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/PaddleCustomDevice#923]
paddle custom device中接入multiclass_nms3时，主框架UT中有一个[NoOutput测例](https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_multiclass_nms_op.py#L792)，自定义算子接入UT时加上这个测例时，无法成功识别output和index的数据，识别为None。

自定义算子输出信息：
<img width="520" alt="ef3643ca92a76703861ae65e260a6aa2" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/87294783/18015c1e-9bc8-4d2f-923a-d03cb617123e">

CPU算子输出信息：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/87294783/31a7cf38-e46e-4d67-829c-7416519f5043)

打开GLOG_V=10，两者主框架侧输出信息tensor信息如下：
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/87294783/cc732c41-59fe-4e03-b146-b13bcdc85102)

最小复现代码，可以直接在multiclass_nms3_kernel.cc自定义注册算子中：
```
out->Resize({0, 6});
ctx.template Alloc<T>(out);

index->Resize({0, 1});
ctx.template Alloc<int>(index);
```

**Comment by ronny1996** [comment]
你好，请问自定义算子实现时是否将out和index作为返回值了？另外注册时使用有注册这2个输出

**Comment by zepingWww** [comment]
> 你好，请问自定义算子实现时是否将out和index作为返回值了？另外注册时使用有注册这2个输出

1. 作为返回值了
2. 这个回答我不太理解是什么意思，注册这两个输出不是在算子输入时就注册好了吗，我在算子内部只需要分配空间就可以了，如下：
```
out->Resize({0, 6});
ctx.template Alloc<T>(out);

index->Resize({0, 1});
ctx.template Alloc<int>(index);
```

**Comment by ronny1996** [comment]
place 是否是 paddle.CustomPlace('xxx')，输出需要在注册op时同时注册，kernel里也需要return

**Comment by qili93** [comment]
超过一周且用户无更多回复的问题自动关闭。

**Comment by zepingWww** [comment]
> place 是否是 paddle.CustomPlace('xxx')，输出需要在注册op时同时注册，kernel里也需要return

@ronny1996
我后来重新看了一下，可能是cpu和custom device的ZeroAllocator有差异，我下面这样的实现可以解决单测问题：
```
  if(ele_length==0)
  {
    dev_ctx.template HostAlloc<T>(out);
  }
  else{
    dev_ctx.template Alloc<T>(out);
  }
```

**Comment by qili93** [comment]
太好了，非常感谢您的支持！
