### ISSUE TITLE
【NPU】notebook import paddle 报错

### ISSUE THREAD

**Issue by bigbosskai** [PaddlePaddle/PaddleCustomDevice#959]
在控制台 /opt/py39/bin/python -c "import paddle" 能正确执行
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/27066989/3aa0b605-0131-4299-b452-b10999ffa45e)
但是在notebook中
import paddle就 不行了
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/27066989/b7cf2df6-3946-4e17-b789-48752bb51a7c)

PATH
LD_LIBRARY_PATH
等环境变量，notebook和控制台都是一致的

**Comment by qili93** [comment]
根据这个错误提示，是由于notebook环境没有正确解析昇腾 CANN 的环境变量导致的

![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/16605440/ca7b7616-ab76-4934-95b0-a4061cde1c09)

在shell环境下的  /root/.bashrc 中，有 `source /usr/local/Ascend/atb/set_env.sh` 用于设置CANN所需的环境变量，可以将这一行命令放到notebook中来设置，或者根据 /usr/local/Ascend/atb/set_env.sh 中的内容手动输出 PATH / LD_LIBRARY_PATH 等环境变量加到notebook中。

**Comment by qili93** [comment]
Close as no more comments in last 7 days.
