### ISSUE TITLE
昇腾310上对PaddlePaddle进行编译失败

### ISSUE THREAD

**Issue by wuys1** [PaddlePaddle/PaddleCustomDevice#965]
是否支持在昇腾310上对PaddlePaddle进行编译？CANN版本应该怎么选？是否有对应的编译环境镜像

**Comment by qili93** [comment]
您好！

CustomDevice没有支持过昇腾310，但是理论上CustomDevice也可以支持昇腾310的芯片，需要修改2个地方

1. 您可以先参考 https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile 目录下的dockerfile文件，将其中昇腾910的安装包替换为310的安装包并构建支持310编译的基础镜像；
2. 然后参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档进行编译，CANN版本建议尽量选择和这个文档中910芯片一致的版本。

您可以尝试验证下，如果在验证过程中有任何问题欢迎随时沟通～

**Comment by qili93** [comment]
hi, 请问你这里有尝试过对310的修改吗？谢谢～～

**Comment by wuys1** [comment]
目前没有，受限于时间节点，后来我们更换硬件进行部署了:) 感谢解答

**Comment by qili93** [comment]
收到，也谢谢您的回复，这个issue我们就关闭了 :)

**Comment by dianziMAN** [comment]
@qili93 你好，我正在基于 https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/tools/dockerfile 这个dockerfile进行310P3芯片的镜像构建，把其中910的部分换成了310p相关的安装包。
Dockerfile.npu.ubuntu20.gcc84 里61~68行里有个 COPY code-share /usr/local/Ascend/code-share/ ，请问这个code-share是什么？该怎么获取？
![a](https://github.com/user-attachments/assets/087fe74e-edf3-4f52-bf5d-bb8e39537d72)
